### ISSUE TITLE
--int8 flag missing on YOLOv8-DeepStream-TRT-Jetson.md

### ISSUE THREAD

**Issue by NoIdeaOfUsername** [Seeed-Studio/wiki-documents#103]
Hi, is `--int8` flag missing [here ](https://github.com/Seeed-Studio/wiki-documents/blame/6e7cb84937576dd1a159e220bbccac17c4149bfb/docs/Edge/reComputer/Application/YOLOv8-DeepStream-TRT-Jetson.md#L412)?

**Comment by MatthewJeffson** [comment]
Hi, may I ask whether you have tested it? or you have followed the wiki and didn't work:D
