### ISSUE TITLE
[Page Add][Enhanced Function]Using the XIAO nRF52840 Sense for Zephyr Applications

### ISSUE THREAD

**Issue by grilliiiii** [Seeed-Studio/wiki-documents#1045]
## Overview
- We need your help to support XIAO nRF52840 Sense for Zephyr Application and write a complete Wiki page for it.

## How do we work together?
- **Leave a comment with your GitHub name below** as you accept this assignment and will complete the contents about what we are trying to present.
- The maintainer will assign and record you as our only contact for this assignment.
- You can first [Deploy this Wiki Platform Locally](https://wiki.seeedstudio.com/Deploy_Page_Locally/) (The entire source code .zip file is only 30 M)
- You will be invited as our **"Contributor"** once you ["Pull Request"](https://wiki.seeedstudio.com/Contribution-Guide/).
- The maintainer will review the PR and then merge.
## What do we offer?
We want to express our gratitude to our contributors by offering a range of rewards.  Depending on the difficulties(Tier 0/1/2/3), the time we expect(Days 1/3/7/15),  the actual  submission time and the actual submission contents, we will offer different levels of rewards.
1. We will provide our products or cash bonus to our contributors as a token of appreciation.
2. For those contributors who join our "Ranger Program"(announced soon), we offer even more exciting rewards, including access to our prototype products.
3. In addition, all contributors and their contributions will be acknowledged and showcased on our wiki platform.
## FAQ
- For any question, the contributor can directly commend here.
### I think I can complete the assignment, but I need more time?
- The timeframe here is based on our old experience, from people who has done it or something like that.
- However, **many projects will take much more time** under actual circumstances (including the main language of the contributors receiving the task and the actual creative difficulty)
- You can leave the time you need and a brief reason, we will evaluate the situation accordingly.

**Comment by Timo614** [comment]
Just a heads up but it appears the zephyr build for at least the NRF 52840 sense is broken. I tried multiple examples but even something as simple as blinky fails with the LED always on. In addition it looks like the USB console isn't working for it as well and I don't have the nicer flashing tooling so may not be able to debug it further. That or I have a bad Xiao NRF 52840 but I haven't had issues previously with my board and arduino.

Could someone confirm if the following works for their board.

From the zephyr directory:
```
west build -p always -b xiao_ble_sense samples/basic/blinky
```

Double tap reset on the board to mount the drive for the uf2.

Move the build/zephyr/zephyr.uf2 to the mounted drive.

Is the LED always on for you as well?

**Comment by Timo614** [comment]
From the looks of issues on zephyr folks have used the xiao_ble recently even so not sure if this is a sense only issue? Or if it's specific to my board? I only have the one xiao_ble_sense board so can't confirm if it's something else. Going to hold off on this for now given I'm blocked here if you want to reassign someone else's way in case they have a good board to test with.
