### ISSUE TITLE
[Bug] CO2 Sensor(Built-in) Page: Example Code Not Running

### ISSUE THREAD

**Issue by lemorage** [Seeed-Studio/wiki-documents#1091]
I copy&paste the example code in the page [CO2 Sensor(Built-in)](https://wiki.seeedstudio.com/SenseCAP_Indicator_RP2040_CO2/), but it simply can't run. The error message is as follows,

```
/private/var/folders/9n/zrq49fmx27l7237gf4kj001h0000gn/T/.arduinoIDE-unsaved202438-13428-7vfs0m.16w3i/sketch_apr8b/sketch_apr8b.ino: In function 'void setup()':
/private/var/folders/9n/zrq49fmx27l7237gf4kj001h0000gn/T/.arduinoIDE-unsaved202438-13428-7vfs0m.16w3i/sketch_apr8b/sketch_apr8b.ino:74:8: error: 'class TwoWire' has no member named 'setSDA'
   Wire.setSDA(20);
        ^~~~~~
/private/var/folders/9n/zrq49fmx27l7237gf4kj001h0000gn/T/.arduinoIDE-unsaved202438-13428-7vfs0m.16w3i/sketch_apr8b/sketch_apr8b.ino:75:8: error: 'class TwoWire' has no member named 'setSCL'
   Wire.setSCL(21);
        ^~~~~~

exit status 1

Compilation error: 'class TwoWire' has no member named 'setSDA'
```

<img width="960" alt="Screenshot 2024-04-09 at 13 44 38" src="https://github.com/Seeed-Studio/wiki-documents/assets/88943827/75378dd6-c35c-4915-a02d-d94fa5b572c7">

**Comment by Love4yzp** [comment]
the wire of Arduino Uno has no Wire.set(), plz check https://docs.arduino.cc/learn/communication/wire;
Which device are you actually using?

RP2040 and esp32 have the function: 
1. https://arduino-pico.readthedocs.io/en/latest/wire.html
2. https://docs.espressif.com/projects/arduino-esp32/en/latest/api/i2c.html?highlight=wire

**Comment by lemorage** [comment]
Okay...I am using the Arduino Uno board, so the code in the tutorial is not applied to this board. Got it, thx.
