### ISSUE TITLE
[Page Add][Enhanced Function]Deploy Frigate on a reComputer(NVIDIA Jetson) device

### ISSUE THREAD

**Issue by MatthewJeffson** [Seeed-Studio/wiki-documents#1238]
## Overview
We need your help to enable users to be able to run `Frigate` smoothly on our reComputer(NVIDIA Jetson devices) and enjoy high-performance real-time object detection. In addition, a complete set of deployment and optimization guidelines should be available to help more users achieve efficient deployment on similar devices.

- Frigate deployment: Successfully deploy `Frigate` on our reComputer device(NVIDIA Jetson), ensuring that its basic functionality is up and running.
- Performance optimization: Frigate was optimized for Jetson's GPU architecture to improve processing speed and efficiency.
- Stability test: Continuous running test to ensure stability and reliability over a long period of time.
- Wiki guidance: Write detailed documentation of the deployment and optimization process, including possible problems and solutions.

## Additions:

We are looking for community contributions to enrich our library of [AI models reComputer(Jetson) devices](https://github.com/luoluoter/jetson-examples). We want to receive model examples that can be deployed and used in an easy way, ideally "one-click deployment." This will make it easier for developers and researchers to test and use various AI models on Jetson devices, accelerating the R&D and innovation process.

## How do we work together?
- **Leave a comment with your GitHub name below** as you accept this assignment and will complete the contents about what we are trying to present.
- The maintainer will assign and record you as our only contact for this assignment.
- You can first [Deploy this Wiki Platform Locally](https://wiki.seeedstudio.com/Deploy_Page_Locally/) (The entire source code .zip file is only 30 M)
- You will be invited as our **"Contributor"** once you ["Pull Request"](https://wiki.seeedstudio.com/Contribution-Guide/).
- The maintainer will review the PR and then merge.
## What do we offer?
We want to express our gratitude to our contributors by offering a range of rewards.  Depending on the difficulties(Tier 0/1/2/3), the time we expect(Days 1/3/7/15),  the actual  submission time and the actual submission contents, we will offer different levels of rewards.
1. We will provide our products or cash bonus to our contributors as a token of appreciation.
2. For those contributors who join our "Ranger Program"(announced soon), we offer even more exciting rewards, including access to our prototype products.
3. In addition, all contributors and their contributions will be acknowledged and showcased on our wiki platform.
## FAQ
- For any question, the contributor can directly commend here.
### I think I can complete the assignment, but I need more time?
- The timeframe here is based on our old experience, from people who has done it or something like that.
- However, **many projects will take much more time** under actual circumstances (including the main language of the contributors receiving the task and the actual creative difficulty)
- You can leave the time you need and a brief reason, we will evaluate the situation accordingly.

**Comment by kouroshkarimi** [comment]
Hi @MatthewJeffson
I think I can complete the assignment, but I need more time. 
I have purchased a Jetson and there may be a delay in its delivery to me.
I have experience with developing detection algorithms on Jetson.

**Comment by MatthewJeffson** [comment]
Wow! Thank you @kouroshkarimi so much for considering this!
I really appreciate it!
We can get started it once your Jetson arrivied:)
Please let me know if you need any help from our side.
Best Regards,
Matthew

**Comment by kouroshkarimi** [comment]
@MatthewJeffson,
I'm thrilled about that! I believe my Jetson will arrive in a few days. I can't wait to start working on it. I have a lot of experience working with Jetson (Orin, Xavier, AGX, Nano), and I bought my own Jetson for this project. I'm very familiar with how to use it.
Could you provide me with some links related to this issue to help me speed up my work? Also, I'm interested in learning more about Seeed Studio's coding principles.

**Comment by MatthewJeffson** [comment]
@kouroshkarimi Nice! And that is awesome you are quite familiar with Jetson! 

We are actually brewing and publishing a number of topics based on Jetson, which as example you can see here:
- [On code deploy model on reComputer](https://github.com/Seeed-Projects/jetson-examples?tab=readme-ov-file)

Regarding this assignment, I think you can refer to [here](https://github.com/blakeblackshear/frigate/pull/11321)
There are still some issues running Frigate on Jetson, like it only uses CPU to do the AI acceleration and not the GPU.

It would be really amazed you can fix or develop something that allows Frigate running smoothly on the Jetson devices, writing to other people a wiki ([template](https://wiki.seeedstudio.com/Name_your_website/)) about the installation. We will present on our wiki platform.:)

Thank you so much!

Best Regards,
Matthew

**Comment by kouroshkarimi** [comment]
Hi @MatthewJeffson,
Frigate's documentation states that it supports Jetsons and utilizes GPU, contradicting your statement that it only uses CPU!
Here is the text :

![Image](https://github.com/Seeed-Studio/wiki-documents/assets/62615112/2fefbad3-0593-4319-bb01-02f28d2760fd)

**Comment by MatthewJeffson** [comment]
Hello! @kouroshkarimi 
I am sorry for the misunderstanding. Frigate does utilize GPU but we used to test a little bit that we were not able to apply it - thus, if you can help us that would be really great! 
Best Regards,
Matthew

**Comment by kouroshkarimi** [comment]
@MatthewJeffson 
That's okay. I will attempt to run it on the Jetson.

**Comment by MatthewJeffson** [comment]
Great! Thank you so much!

**Comment by kouroshkarimi** [comment]
@MatthewJeffson 
I started coding on Jetson Xavier NX with JP5. I ran the Frigate Docker with TensorRT and obtained the following outputs. It ran with GPU TensorRT for its detector.

![Image](https://github.com/Seeed-Studio/wiki-documents/assets/62615112/91491438-05b8-4bde-98d8-6d978890c7dd)
![Image](https://github.com/Seeed-Studio/wiki-documents/assets/62615112/b3b9e81d-7c31-48d2-b14b-69e1abfe05d2)

**Comment by kouroshkarimi** [comment]
Hi @MatthewJeffson 
I deployed Frigate on the Nvidia Jetson. How can I receive a response about it?
Is it OK or need more optimization?

**Comment by MatthewJeffson** [comment]
Wow! That is quickly amazing! @kouroshkarimi  Thank you so much! 
You can deploy it near to you then detect some common objects and then do some triggering action:

Like detecting the person running, walking, etc - You can use some common existed ML models.

Or you can train one for it - And if you do that, would you mind as well writing a tutorial about the trainning?

Thanks! 

Best Regards,
Matthew

**Comment by feiticeir0** [comment]
Is this still available  ?

**Comment by kouroshkarimi** [comment]
@MatthewJeffson 
Sure, I will go for that. Thank you for your reply.

**Comment by kouroshkarimi** [comment]
Hi @MatthewJeffson 
I have a question about "Detecting the person running, walking, etc." Do you mean running will be a class and walking is another class, or just detecting the person in general?

**Comment by kouroshkarimi** [comment]
@MatthewJeffson
I deploy it and post its result on LinkedIn. If detecting a person is enough I can write its wiki now.

**Comment by yuyoujiang** [comment]
Hi @kouroshkarimi , I'm an application engineer of SeeedStuido. Thank you very much for this work.
I think it's time to write a wiki to share this project. 
It would be better if the article included a short video to demonstrate the project's features.
@MatthewJeffson has already shared the [wiki template](https://wiki.seeedstudio.com/Name_your_website/) with you. If you need more reference material, please refer to [here](https://wiki.seeedstudio.com/Local_Voice_Chatbot/).

**Comment by kouroshkarimi** [comment]
Hi @yuyoujiang
Thank you for responding. I will proceed with that.

**Comment by MatthewJeffson** [comment]
Hello! @kouroshkarimi I just got back to the office.
Thanks for the proceeding:)
Best Regards,
Matthew

**Comment by kouroshkarimi** [comment]
Hi @MatthewJeffson 
I wrote a wiki for it and requested for merge. if it needs to change please tell me to correct it.

**Comment by MatthewJeffson** [comment]
Thank you! @kouroshkarimi  We will check it very soon!
By the way, once it merged, would you mind I adding this project in our [Contributor Page](https://wiki.seeedstudio.com/contributors/)? 
![image](https://github.com/user-attachments/assets/a1c9ae64-1219-4224-9d07-09e8fcd5bccb)

And we sincerely want to offer cash bonus or products as compensation, may we communicate through email? jianfeng.yu@seeed.cc

Best Regards,
Matthew

**Comment by yuyoujiang** [comment]
Nice work @kouroshkarimi !!!
I noticed that your PR does not include a demonstration video. It would be helpful if you could record a video showing how to start Frigate, add cameras, and integrate models, among other tasks. And your demonstration video might be featured on Seeed's official social media channels.

**Comment by kouroshkarimi** [comment]
Hi @MatthewJeffson 
Sure. I'll be happy if you add it.  thank you for your compensation. Yes, it is ok to communicate through email. I will wait for your email.

**Comment by kouroshkarimi** [comment]
Hi @yuyoujiang
Sure, I will record it in the coming days. Where should I upload the video, and can you provide me with a sample video? I just want to understand the video timing and type of recording.

**Comment by yuyoujiang** [comment]
Hi @kouroshkarimi , here have some sample videos. Just show the end result.
https://www.youtube.com/watch?v=niS0TLzyn-s
https://youtu.be/MLPE9V3GKK0?si=wIEuACqYqT_jalwv
https://www.youtube.com/@SeeedStudioSZ

Don't be limited by these reference videos, the only requirement for this video is to show the final result, you can also design the video as you want.
