### ISSUE TITLE
[Page Update][Basic function] Fix and enable the Grove Pi Hat to run stably on Raspberry Pi 4

### ISSUE THREAD

**Issue by MatthewJeffson** [Seeed-Studio/wiki-documents#1242]
## Updated
The repo [grove.py](https://github.com/Seeed-Studio/grove.py) has been updated.

## Overview
- It was discovered that because UPM and MRAA libraries do not export correctly on Raspberry Pi 4, The Grove Pi Hat support on Pi 4 devices has serious problems.
- We need your help to enable the [Grove Pi Hat](https://www.seeedstudio.com/Grove-Base-Hat-for-Raspberry-Pi.html) to run stably on Raspberry Pi 4, maintaining its usability and user experience.
- We are actually improving this by ourself and we are welcome additional perspective ideas.
## How do we work together?
- **Leave a comment with your GitHub name below** as you accept this assignment and will complete the contents about what we are trying to present.
- The maintainer will assign and record you as our only contact for this assignment.
- You can first [Deploy this Wiki Platform Locally](https://wiki.seeedstudio.com/Deploy_Page_Locally/) (The entire source code .zip file is only 30 M)
- You will be invited as our **"Contributor"** once you ["Pull Request"](https://wiki.seeedstudio.com/Contribution-Guide/).
- The maintainer will review the PR and then merge.
## What do we offer?
We want to express our gratitude to our contributors by offering a range of rewards.  Depending on the difficulties(Tier 0/1/2/3), the time we expect(Days 1/3/7/15),  the actual  submission time and the actual submission contents, we will offer different levels of rewards.
1. We will provide our products or cash bonus to our contributors as a token of appreciation.
2. For those contributors who join our "Ranger Program"(announced soon), we offer even more exciting rewards, including access to our prototype products.
3. In addition, all contributors and their contributions will be acknowledged and showcased on our wiki platform.
## FAQ
- For any question, the contributor can directly commend here.
### I think I can complete the assignment, but I need more time?
- The timeframe here is based on our old experience, from people who has done it or something like that.
- However, **many projects will take much more time** under actual circumstances (including the main language of the contributors receiving the task and the actual creative difficulty)
- You can leave the time you need and a brief reason, we will evaluate the situation accordingly.

**Comment by quietCoder500** [comment]
@quietCoder500. Hi, I would like to attempt to solve this issue. This is my first time working on an issue for Seeed Studios so it might take me longer than a week. I do not have a grove hat but I will try to still test it as best as I can.

**Comment by quietCoder500** [comment]
@MatthewJeffson, I have tested out a [patch](https://github.com/Seeed-Studio/grove.py/pull/75) that failed and it seems that several sections of grove.py will need a complete overhaul. I am willing to undertake this but I do not have a time estimate. This issue has been stale for two months so that should not be too big of a problem.

**Comment by MatthewJeffson** [comment]
Pleasure to meet you! @quietCoder500 
We are actually improving this by ourself and we are welcome additional perspective ideas:)

Do you have a Pi 4 with you right now? Here we can work this out:
1. I can send you one Grove Pi HAT or offer you a coupon then you can test it on your Pi 4
2. a. For we haven't released the new version, once you have a stable patch you can PR to the [repo of the board](https://github.com/Seeed-Studio/grove.py), we can then have a brief settlement:)
2. b.  For we have released the new version, if you can help us supporting more Grove modules for it, we will be really appreciated it and we will offer the compensation as well.

Would you mind joining us the Discord channel for more direct communcation? Here is my ID:

matthew_yu0310



![Image](https://github.com/user-attachments/assets/872ecca2-008d-4b4d-9724-8672e30271a0)


Looking forward to work with you!
Best Regards,
Matthew

**Comment by quietCoder500** [comment]
Thanks @MatthewJeffson, I have already submitted a pr to the repository of the board. Pull request [number 76](https://github.com/Seeed-Studio/grove.py/pull/76). I have both a Raspberry Pi 4 & 5 that I can test on. I will message you on discord when I can. There is a twelve hour difference in time zones between our locations however, so I might not respond until the next day.

**Comment by MatthewJeffson** [comment]
No problem at all! @quietCoder500 I may as well have a late response sometimes:)
