### ISSUE TITLE
Force Recovery mode in A203 Mini PC?

### ISSUE THREAD

**Issue by AhmedFawzy0** [Seeed-Studio/wiki-documents#129]
### Discussed in https://github.com/Seeed-Studio/wiki-documents/discussions/128

<div type='discussions-op-text'>

<sup>Originally posted by **AhmedFawzy0** April  7, 2023</sup>
There is no recovery key, how can I force recovery??
Just power and reset doesn't work

<img width="806" alt="image" src="https://user-images.githubusercontent.com/89322519/230556373-4be91e8b-7004-4110-a562-722d0548bade.png">
</div>

**Comment by MatthewJeffson** [comment]
Hi, on the Step 4, the "Recovery Key" really should be "Reset Key". I have changed that. Thank you for pointing it out!

**Comment by AhmedFawzy0** [comment]
Regardless, I tried it many times, it is not going into force recovery. Where is the LED? No matter how long I hold both buttons for, no light…

I have the newer A203 does this way only work for the A203E only??

do you recommend opening it up and manually connecting the 2 recovery pins ?

Thanks

**Comment by MatthewJeffson** [comment]
Hi, my colleague has confirmed that the steps are feasible. Would you mind test for a few more times? Or you can contact the tech support: fae@seeed.cc <br/> Thank you!

**Comment by AhmedFawzy0** [comment]
Will try again, could you ask the people who did this before, where the LED is ? Is it the buttons themselves that lightup ?
