### ISSUE TITLE
[SeeedStudio_Round_Display_for_XIAO.md] wrong file name to include

### ISSUE THREAD

**Issue by matsujirushi** [Seeed-Studio/wiki-documents#132]
**Location:**
https://wiki.seeedstudio.com/get_start_round_display#software-preparation

**Content:**
If you want to use the **TFT_eSPI** library for display driving, you must **comment out** the line `#include <User_Setup.h>` and uncomment the line `#include <User_Setups/Setup66_Seeed_XIAO_RoundDisplay.h>` in the `User_Setup_Select.h` file.

**Description:**
**Setup66_Seeed_XIAO_RoundDisplay.h** is not included in [TFT_eSPI](https://github.com/Maxwelltoo/TFT_eSPI).
Isn't it [**Setup66_Seeed_XIAO_Round.h**](https://github.com/Maxwelltoo/TFT_eSPI/blob/master/User_Setups/Setup66_Seeed_XIAO_Round.h)?

**Comment by MatthewJeffson** [comment]
Wow! Thank you for pointing it out! I will double check with guy who wrote it :D
