### ISSUE TITLE
Add two boards on Fritzing library: LoRa-E5 Development Kit and LoRa-E5 Mini

### ISSUE THREAD

**Issue by MatthewJeffson** [Seeed-Studio/wiki-documents#1402]
## Overview

We need your help to add these parts to the [Fritzing](http://fritzing.org/), the popular open-source software tool.
- LoRa-E5 Development Kit : https://www.seeedstudio.com/LoRa-E5-Dev-Kit-p-4868.html
- LoRa-E5 Mini : https://www.seeedstudio.com/LoRa-E5-mini-STM32WLE5JC-p-4869.html 

reference: https://github.com/Seeed-Studio/fritzing_parts/issues/10

We will require more our products presenting Fritzing and welcome to contribute to our [Fritzing GitHub Repo](https://github.com/Seeed-Studio/fritzing_parts)!

## How do we work together?
- **Leave a comment with your GitHub name below** as you accept this assignment and will complete the contents about what we are trying to present.
- The maintainer will assign and record you as our only contact for this assignment.
- You can first [Deploy this Wiki Platform Locally](https://wiki.seeedstudio.com/Deploy_Page_Locally/) (The entire source code .zip file is only 30 M)
- You will be invited as our **"Contributor"** once you ["Pull Request"](https://wiki.seeedstudio.com/Contribution-Guide/).
- The maintainer will review the PR and then merge.
## What do we offer?
We want to express our gratitude to our contributors by offering a range of rewards.  Depending on the difficulties(Tier 0/1/2/3), the time we expect(Days 1/3/7/15),  the actual  submission time and the actual submission contents, we will offer different levels of rewards.
1. We will provide our products or cash bonus to our contributors as a token of appreciation.
2. For those contributors who join our ["Ranger Program"](https://wiki.seeedstudio.com/ranger/), we offer even more exciting rewards, including access to our prototype products.
3. In addition, all contributors and their contributions will be acknowledged and showcased on our wiki platform.
## FAQ
- For any question, the contributor can directly commend here.
### I think I can complete the assignment, but I need more time?
- The timeframe here is based on our old experience, from people who has done it or something like that.
- However, **many projects will take much more time** under actual circumstances (including the main language of the contributors receiving the task and the actual creative difficulty)
- You can leave the time you need and a brief reason, we will evaluate the situation accordingly.

**Comment by gokuxmaker** [comment]
Hi @MatthewJeffson let me in

**Comment by MatthewJeffson** [comment]
Oh! Hi! @gokuxmaker Nice and thank you for doing this:)

**Comment by gokuxmaker** [comment]
Done
https://github.com/Seeed-Studio/fritzing_parts/pull/15
![image](https://github.com/user-attachments/assets/40dfd844-eaec-4ce5-8e14-05ac0ea32887)
