### ISSUE TITLE
[Seeed Studio XIAO ESP32S3]  2 similar indexes

### ISSUE THREAD

**Issue by matsujirushi** [Seeed-Studio/wiki-documents#154]
Like the Seeed Studio XIAO nRF52840, wouldn't it be better to combine them into one?

* SeeedStudio XIAO ESP32S3 (Sense)
* SeeedStudio XIAO ESP32S3 Sense

![image](https://user-images.githubusercontent.com/8079404/232352422-ddb124c6-29a9-4b64-b3f6-e818a62b725c.png)

**Comment by MatthewJeffson** [comment]
Hi, this indeed is an interesting question :D <br/> I will contact the person who wrote it
