### ISSUE TITLE
[Page Add][Enhanced function] Support Meshtastic for SenseCAP Indicator

### ISSUE THREAD

**Issue by MatthewJeffson** [Seeed-Studio/wiki-documents#1640]
## Overview
- Support Meshtastic for [SenseCAP Indicator D1L](https://www.seeedstudio.com/SenseCAP-Indicator-D1L-p-5646.html) 
- Implement the latest UI interface and the basic functions of Meshtastic.
## ✨ Assigned Contributor

This assignment is presented on the [Contributor Page](https://wiki.seeedstudio.com/contributors/) and been accepted and already assigned one contributor.

![Image](https://github.com/user-attachments/assets/9995d139-1ecb-456e-80f1-b75790f887d8)

## [The Contribution(Pull Request) Guide](https://wiki.seeedstudio.com/Contribution-Guide/)

1. [Deploy Wiki Platform Locally](https://wiki.seeedstudio.com/Deploy_Page_Locally/)
2. [Full Steps Pull Request](https://wiki.seeedstudio.com/full_steps_pull_request/) - Do the changes or add the files, while **seeing the changes locally**. Then PR to our repo.
4. [Quick Pull Request](https://wiki.seeedstudio.com/quick_pull_request/) - You can just download all required files and add md file as well as images, then **direct PR** to our repo.

## What do we offer?
We want to express our gratitude to our contributors by offering a range of rewards.  Depending on the difficulties(Tier 0/1/2/3), the time we expect(Days 1/3/7/15),  the actual  submission time and the actual submission contents, we will offer different levels of rewards.
1. We will provide our products or cash bonus to our contributors as a token of appreciation.
2. For those contributors who join our "Ranger Program"(announced soon), we offer even more exciting rewards, including access to our prototype products.
3. In addition, all contributors and their contributions will be acknowledged and showcased on our wiki platform.
## FAQ
For the ranger who accepts this assignment can have a conversation with your transition AE below

**Comment by mverch67** [comment]
The first part is finished, the PR to support SenseCAP Indicator has been merged into meshtastic master branch and will be available in firmware 2.5.1:
https://github.com/meshtastic/firmware/pull/4279

The required changes for the io expander support can be found in a fork of arduino-esp32, branch _add_tca9535_ which eventually will be adopted by the meshtastic organisation.
https://github.com/mverch67/arduino-esp32/tree/add_tca9535

The second part (SenseCAP Indicator with the new meshtastic UI) is implemented in a UI library
https://github.com/meshtastic/device-ui

and can be built using the following meshtastic PR branch, target _seeed-sensecap-indicator-tft_:
https://github.com/meshtastic/firmware/pull/3259/

As the meshtastic device-ui development is an ongoing process for a couple of other supported devices (using common code!) and there are still bugs and unfinished implementations and features, the SenseCAP Indicator UI will evolve further until this feature will be released by meshtastic and the feature PR is merged into master branch.

**Comment by eerke2021** [comment]
Is this the Indicator with built in LoRaWAN or a standard indicator with a Grove LoRa attached also? The indicator has grove ports and I have a spare Grove LoRa.

**Comment by MatthewJeffson** [comment]
Hi! @mverch67 The Indicator we needed is capable of LoRa communicating and current no need sensors onboard.

And thank you so much @mverch67 for doing this. It is really amazing!

Best Regards,
Matthew

**Comment by eerke2021** [comment]
But all models of Indicator have Grove connectors, which means you could connect all of them to a "Grove-Wio-E5 Wireless Module - STM32WLE5JC, ARM Cortex-M4 and SX126x embedded, supports LoRaWAN on EU868 & US915". Is this project about utilising the Indictator with built in LoRa only or all of them if they are connected to the Grove LoRa?

**Comment by MatthewJeffson** [comment]
Yes @eerke2021 and that will be next step moving:D

Currently we need the latest Meshtastic UI and support the expansion chip on the Indicator. Once the Indicator handle the normal Meshtastic sending and outputting will be fine:D

These steps will take quite a time to finish.
