### ISSUE TITLE
Step file or technical drawing for Grove - CO2 & Temperature & Humidity Sensor (SCD41)

### ISSUE THREAD

**Issue by matthias-bs** [Seeed-Studio/wiki-documents#1705]
**Is your feature request related to a problem? Please describe.**
I want to integrate the module into a 3D printed case. To achieve optimal sensor readings, the placement must be designed to assure the airflow as specified by Sensirion, therefore the mechanical integration is not trivial. On 
https://wiki.seeedstudio.com/Grove-CO2_&_Temperature_&_Humidity_Sensor-SCD41/, only a STEP file of the sensor without the module PCB is provided.

**Describe the solution you'd like**
A STEP file would be great, but even a technical drawing with the PCB outlines and thickness, mounting holes and sensor position would be helpful.

**Comment by MatthewJeffson** [comment]
Hi! @matthias-bs  I think the PCB file is here https://files.seeedstudio.com/wiki/Grove-CO2&Temperature&HumiditySensor-SCD4/res/SCH&PCB.zip
Thanks!

**Comment by matthias-bs** [comment]
The PCB file is in a proprietary format. I was able to view it with some freely available software / web tool, but I was not able to extract the required dimensions or to export a mechanical drawing or 3D model.
