### ISSUE TITLE
TimeStamp not correct

### ISSUE THREAD

**Issue by RakiDelmoro** [Seeed-Studio/wiki-documents#1784]
Hi everyone I have a SenseCap Indicator D1 version. I already Setup and connected to wifi and I think I do it correctly since I'm relying on wiki seeed studio. But the TimeStamp of my SenseCap is not right. It's advance 4hours.

**Comment by RakiDelmoro** [comment]
Anyone know how to fix this issue? Or anyone have the same problem. Thanks!

**Comment by MatthewJeffson** [comment]
Hello @RakiDelmoro Raki! Sorry for the delay response. I will contact someone.
Best Regards,
Matthew

**Comment by Love4yzp** [comment]
The issue you're facing with the SenseCAP Indicator timestamp being 4 hours ahead is likely related to how the UTC time is fetched and formatted. This problem can occur if the UTC retrieved based on the device's IP address isn’t correctly processed or adjusted in the code. Here’s how you can address it:

1. **Check the UTC Formatting**: In the SenseCAP Indicator’s code, there may be an issue with how the UTC is formatted. Adjusting the `snprintf` line to properly format the UTC should resolve this. For similar guidance, refer to [Issue #25](https://github.com/Seeed-Solution/SenseCAP_Indicator_ESP32/issues/25), where a fix is provided.

2. **Manual UTC Setting**: Alternatively, you can hard-code the UTC if the API fetching method isn’t working as expected.

3. **Refer to Other Issues**: The [Issue #48](https://github.com/Seeed-Solution/SenseCAP_Indicator_ESP32/issues/48) may also have relevant information and similar troubleshooting tips that could help.

Try these steps, and if the problem persists, feel free to reach out again!
