### ISSUE TITLE
[Page Add][Enhanced Function]Adding boards to Flux.ai and fritzing, as well as 3D models design

### ISSUE THREAD

**Issue by MatthewJeffson** [Seeed-Studio/wiki-documents#1901]
## Overview
- We need your help to add required Boards in the [Flux.ai](https://www.flux.ai/seeedstudio):
1. 24GHz mmWave Sensor for XIAO
2. Seeed Studio 6x10 RGB MATRIX for XIAO
3. Seeed Studio XIAO CAN Bus Breakout Board
4. Seeed Studio ePaper Breakout Board
5. Seeed Studio Grove Base for XIAO
6. Seeed Studio Expansion Board Baase
7. Seeed StudioXIAO MG24 board

- And we need your help to add XIAO MG24 to the [fritzing](https://github.com/Seeed-Studio/fritzing_parts)
- We may not have the 3D models, and if there is anyone related. We may need it to be designed.

Reference:
- [XIAO SAMD21 on Flux.ai(by amazing cnaville89)](https://www.flux.ai/cnaville89/seeed-xiao-samd21?editor=pcb_3d)
- [Move your KiCAD parts into Flux](https://www.youtube.com/watch?v=eplpLndGfvk)

## How do we work together?
- **Leave a comment with your GitHub name below** as you accept this assignment and will complete the contents about what we are trying to present.
- You can refer to the [Contributor Program](https://wiki.seeedstudio.com/Contributor/) page for more details receiving.
- We have presented two ways to [PR to this repo](https://wiki.seeedstudio.com/Contribution-Guide/).
- You will be invited as our **"Contributor"** once you ["Pull Request"](https://wiki.seeedstudio.com/Contribution-Guide/).
- The maintainer will review the PR and then merge.
## What do we offer?
We want to express our gratitude to our contributors by offering a range of rewards.  Depending on the difficulties(Tier 0/1/2/3), the time we expect(Days 1/3/7/15),  the actual  submission time and the actual submission contents, we will offer different levels of rewards.
1. We will provide our products or cash bonus to our contributors as a token of appreciation.
2. For those contributors who join our ["Ranger Program"](https://wiki.seeedstudio.com/ranger/), we offer even more exciting rewards, including access to our prototype products.
3. In addition, all contributors and their contributions will be acknowledged and showcased on our wiki platform.
## FAQ
- For any question, the contributor can directly commend here.
### I think I can complete the assignment, but I need more time?
- The timeframe here is based on our old experience, from people who has done it or something like that.
- However, **many projects will take much more time** under actual circumstances (including the main language of the contributors receiving the task and the actual creative difficulty)
- You can leave the time you need and a brief reason, we will evaluate the situation accordingly.

**Comment by gokuxmaker** [comment]
24GHz mmWave Sensor for XIAO : https://www.flux.ai/seeedstudio/24ghz-mmwave-sensor-for-xiao
Seeed Studio 6x10 RGB MATRIX for XIAO : https://www.flux.ai/seeedstudio/seeed-studio-6x10-rgb-matrix-for-xiao
Seeed Studio XIAO CAN Bus Board : https://www.flux.ai/seeedstudio/seeed-studio-xiao-can-bus-breakout-board
Seeed Studio ePaper Breakout Board : https://www.flux.ai/seeedstudio/seeedstudio-epaper-breakout-board
Seeed Studio Grove Base for XIAO : https://www.flux.ai/seeedstudio/seeed-studio-grove-base-for-xiao
Seeed Studio Expansion Board Base : https://www.flux.ai/seeedstudio/seeed-studio-expansion-board-base
Seeed StudioXIAO MG24 board : https://www.flux.ai/seeedstudio/seeed-studio-xiao-mg24
Seeed StudioXIAO MG24 Sense : https://www.flux.ai/seeedstudio/seeed-studio-xiao-mg24-sense
Seeed StudioXIAO MG24 Sense 3d model :https://grabcad.com/library/seeed-studio-xiao-mg24-sense-1

**Comment by gokuxmaker** [comment]
XIAO MG24 to the fritzing : [Add files via upload #19 ](https://github.com/Seeed-Studio/fritzing_parts/blob/master/XIAO%20Boards/Seeed%20Studio%20XIAO%20MG24.fzpz)

**Comment by MatthewJeffson** [comment]
NICE! Really nice~ @gokuxmaker
