### ISSUE TITLE
[Project Wanted]Make a computer host status monitor using XIAO ESP32S3 and  Round Display for XIAO

### ISSUE THREAD

**Issue by MatthewJeffson** [Seeed-Studio/wiki-documents#315]
## Overview
- Use [XIAO ESP32S3](https://www.seeedstudio.com/XIAO-ESP32S3-p-5627.html) and [Round Display for XIAO](https://www.seeedstudio.com/Seeed-Studio-Round-Display-for-XIAO-p-5638.html) to make a computer host status monitor
- Display as much computer status information as possible on the Round Display, such as CPU usage, memory usage, temperature, etc
- Try to make the interface as cool as possible
## Assignment acceptance
- Please check the "assignee" section before accepting to see if this has already been accepted.
- Please ensure that the **requested timeline** aligns with your workflow.
- Leave your **Github Name** below to indicate that you are willing to accept the job.
- If you are taking on the assignment **for the first time**, you may receive an invitation in your GitHub mail.
## Requirements(check list)
- Prove of video presentation
- Detailed operation procedure written in **Markdown file** with [wiki standards](https://files.seeedstudio.com/wiki/wiki-ranger/Standards_of_Product_ApplicationWiki_Upload.pdf)
- Upload wiki markdown file to GitHub repository with [guide & instructions](https://wiki.seeedstudio.com/Contribution-Guide/)
- List of products used
- Code files that complete the program
## What do we offer?
We want to express our gratitude to our contributors by offering a range of rewards.  Depending on the difficulties(Tier 0/1/2/3), the time we expect(Days 1/3/7/15),  the actual  submission time and the actual submission contents, we will offer different levels of rewards.
1. We will provide our products or cash bonus to our contributors as a token of appreciation.
2. For those contributors who join our "Ranger Program"(announced soon), we offer even more exciting rewards, including access to our prototype products.
3. In addition, all contributors and their contributions will be acknowledged and showcased on our wiki platform.
## FAQ
For the ranger who accepts this assignment can have a conversation with your transition AE below

**Comment by Zachay-NAU** [comment]
Zachary wants to do this!😍

**Comment by MatthewJeffson** [comment]
Hi! Welcome to the Ranger Program! We will get back to you as soon as possible! :D

**Comment by MatthewJeffson** [comment]
Done by [Rupert Hirst](https://hackaday.io/hacker/2010-rupert-hirst) and here is the [project link](https://hackaday.io/project/19018-phatstats-pc-performance-tft-display/log/220526-phat-stats-now-compatible-with-wio-terminal-and-seeed-xiao-round-display)
