### ISSUE TITLE
[Page Add][Enhanced function] Use XIAO ESP32C3 programmed with MicroPython, design a lightning detector with Grove - Lightning Sensor

### ISSUE THREAD

**Issue by MatthewJeffson** [Seeed-Studio/wiki-documents#334]
# This assignment has been successfully achieved 🎉

Thanks Zachay and the wiki page is: https://wiki.seeedstudio.com/XIAO_ESP32C3_MicroPython/

## Overview
- Use [XIAO ESP32C3](https://www.seeedstudio.com/Seeed-XIAO-ESP32C3-p-5431.html) programmed with MicroPython[(GitHub repo here)](https://github.com/IcingTomato/micropython_xiao_esp32c3) 
- Design a lightning detector with [Grove - Lightning Sensor](https://www.seeedstudio.com/Seeed-XIAO-ESP32C3-p-5431.html) 
## Assignment acceptance
- Please check the "assignee" section before accepting to see if this has already been accepted.
- Please ensure that the **requested timeline** aligns with your workflow.
- Leave your **Github Name** below to indicate that you are willing to accept the job.
- If you are taking on the assignment **for the first time**, you may receive an invitation in your GitHub mail.
## Requirements(check list)
- Prove of video presentation
- Detailed operation procedure written in **Markdown file** with [wiki standards](https://files.seeedstudio.com/wiki/wiki-ranger/Standards_of_Product_ApplicationWiki_Upload.pdf)
- Upload wiki markdown file to GitHub repository with [guide & instructions](https://wiki.seeedstudio.com/Contribution-Guide/)
- List of products used
- Code files that complete the program
## What do we offer?
We want to express our gratitude to our contributors by offering a range of rewards.  Depending on the difficulties(Tier 0/1/2/3), the time we expect(Days 1/3/7/15),  the actual  submission time and the actual submission contents, we will offer different levels of rewards.
1. We will provide our products or cash bonus to our contributors as a token of appreciation.
2. For those contributors who join our "Ranger Program"(announced soon), we offer even more exciting rewards, including access to our prototype products.
3. In addition, all contributors and their contributions will be acknowledged and showcased on our wiki platform.
## FAQ
For the ranger who accepts this assignment can have a conversation with your transition AE below

**Comment by Zachay-NAU** [comment]
Zachary wants to do this!😍

**Comment by MatthewJeffson** [comment]
Hi! Welcome to the Ranger Program! We will get back to you as soon as possible! :D

**Comment by MatthewJeffson** [comment]
Hi, I believe the simples have been sent to you

**Comment by Zachay-NAU** [comment]
I have 3 questions: 1. about esp32c3 output: the serial output always shows esp32c3 chip information instead of sensor data
2.There is no workable AS3935 library in micropython for esp32c3 3. There is no workable Air530 library in micropython for esp32c3.

Thanks,

Zac

**Comment by MatthewJeffson** [comment]
Hi, the original idea is coming up with a wiki regarding XIAO ESP32C3 with micropython. What supportable sensor libraries did you find? Maybe we can work on that.

**Comment by Zachay-NAU** [comment]
The project has been completed.
You can find here: [https://github.com/Zachay-NAU/XIAO_ESP32C3_Wifi_Tracker](https://github.com/Zachay-NAU/XIAO_ESP32C3_Wifi_Tracker)

**Comment by Zachay-NAU** [comment]
Here is a demo vedio:[https://www.youtube.com/watch?v=7n72Knh4IIM](https://www.youtube.com/watch?v=7n72Knh4IIM)

**Comment by Zachay-NAU** [comment]
Here is a demo video: [Here is a demo vedio:https://www.youtube.com/watch?v=7n72Knh4IIM](https://www.youtube.com/watch?v=7n72Knh4IIM)

**Comment by MatthewJeffson** [comment]
So excited to see that! 
Nice work!

**Comment by MatthewJeffson** [comment]
I have tested it and all seems fine. Will configure and add the wiki soon.
Thanks!
