### ISSUE TITLE
[Proposal] SenseCAP 2 + SenseCAP Lorawan OutDoor Gateway + Local MQTT instance

### ISSUE THREAD

**Issue by vongomben** [Seeed-Studio/wiki-documents#349]
Hi. 
A request from a possible customers is requesting this scenario.
I have everything in house and interested in testing this (I have never tested the pairing of sernsecap 2 with a private Lorawan Network nor the Chirpstack mode on the Gateway. 

This is something that was indeed much requested by many industrial users, because the normally don't want to rely on Helium / TTN / SenseCAP Cloud. 

Would this be interesting for Seeed as well as a wiki article? 

![diagram](https://github.com/Seeed-Studio/wiki-documents/assets/1215847/da5650cf-a864-4073-89ae-e4186b550250)

**Comment by peterpanstechland** [comment]
Yes, Please, 
Current We have tested the setup you have drawn in the image with reTerminal DM and Sensecap Lora gateway, where the Chirpstack service is running on reTerminal DM and Sesncap Gateway is set to point to the IP Address and port of the Chirpstack service running on the reTemrinal DM and also display the data received from the senceCAP sensors through MQTT broker running on the reTerminal DM. 
I am appreciated If you could provide a wiki article on how to setup the local Chripstack service, and I am really glad to see that you have point this setup out which approves the work we have done is meaningful, I can share with you my flows and also lets work on this wiki article to help the community together.
BTW I am the application engineer at Seeed Studio in charge of the EDGE product line (ARM SBCS such as raspberry pi related and Linkstar series, etc.).
Peter

**Comment by vongomben** [comment]
Hi Peter Pan from Tech Land-

> BTW I am the application engineer at Seeed Studio in charge of the EDGE product line (ARM SBCS such as raspberry pi related and Linkstar series, etc.).

I love what you have been doing! Edge line is such an inspiring product line, and is partially based on Node-RED which is something I've been telling /lookinh for years. 

Here are some of the thoughs about our reply. 

> Current We have tested the setup you have drawn in the image with reTerminal DM and Sensecap Lora gateway, where the Chirpstack service is running on reTerminal DM and Sesncap Gateway is set to point to the IP Address and port of the Chirpstack service running on the reTemrinal DM and also display the data received from the senceCAP sensors through MQTT broker running on the reTerminal DM.

1) would this work on a standard reTErminal?
2) Sensecap Lora Gateway is [this one ](https://wiki.seeedstudio.com/Network/SenseCAP_Network/Sensecap-LoRaWAN-Gateway-and-Wireless-Sensor-User-Guide/) right? 
3) Can you confir that the scenario you were depicting (and the one I am, to an extent) is totally happening locally without using Sensecap or any other cloud other thatn that LAN?
4) I remember (but I'm unable to find it now) that  Sensecap Lora Gateway could host a Chirpstack server itself. This memory dates back to 2021, maybe is not anymore so.

Waiting for the answers to these points, but I'm willing to contribute to this article. 

best

**Comment by MatthewJeffson** [comment]
We will consider it carefully and get back to you as soon as possible. 
But first would you mind receive GitHub collaborator invitation and see whether there are any [reward projects that exist](https://github.com/orgs/Seeed-Studio/projects/5/views/1) that you'd like to do?
