### ISSUE TITLE
[proposal][Updated] List of possible events to join in end of 23 beginning 24 (please add)

### ISSUE THREAD

**Issue by vongomben** [Seeed-Studio/wiki-documents#369]
## Promotional Marketing Activities (EU)

We could bering workshops here, or having a stand (tougher and more expensive) [UPDATED]

| Date          | Location      | Name                           | Description / Notes                                                                                  | Attendees (expected)                                                                       | link                                                            |
| ------------- | ------------- | ------------------------------ | ---------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------ | --------------------------------------------------------------- |
| 26-28 Sept 23 | Dortmund, DE  | Vertifarm                      | International trade fair for next level farming and new food systems                                 | 3-4K, [here is last year report](https://www.vertifarm.de/vertifarm-debut-a-great-success) | [link](https://www.vertifarm.de/)                               |
| ~~11-12 Oct 23~~   | ~~Frankfurt, DE~~ | ~~Natural Disaster Expo (Europe)~~ | ~~Maybe moved to May? Wrote them~~                                                                       | ~~3000 [Exhibitors expected](https://www.disasterexpoeurope.com/news/56576/)~~                 | [link](https://www.naturaldisastersshow.de/index.asp)           |
| 20-22 Oct 23  | Rome, IT      | Maker Faire Rome               | Maybe making an off event on the firday or saturday night? Pinging people                            |                                                                                            | [link](https://makerfairerome.eu/en/) 
| 30 Oct 23  | Amsterdam, IT      | Helium House               | Official Helium Event in Europe               |                                                                                            | [link](https://www.helium.com/house)                           |
| 7-9 Nov 23    | Barcelona, ES | Smart City Expo                | Smart City Expo World Congress is the world’s biggest and most influential event on urban innovation |                                                                                            | [link](https://www.smartcityexpo.com/)                          |
| 14-16 Nov 23  | Tallin, EE    | Cleantech Forum Europe         | Apparently one of the top event sin Europe on the topic                                              | [last year agenda](http://cleantech.com/event/cleantech-forum-europe-brussels/#agenda-1)   | [link](https://www.cleantech.com/event/cleantech-forum-europe/) |
| 9-11 April 24 | Bergamo, IT   | Waste Management Europe        |                                                                                                      | [5-8K Professionals and buyers](https://wme-expo.com/who-exhibit/)                         | [link](https://wme-expo.com/who-exhibit/)                       |
| ~~15-16 May 24~~  | ~~Frankfurt, DE~~ | ~~Natural Disaster Expo (Europe)~~ | ~~Apparently this is confirmed~~                                                                         | ~~3000 Exhibitors expected~~                                                                   | [link](https://www.naturaldisastersshow.de/index.asp)           |

**Comment by vongomben** [comment]
The Disaster event is in May. The organizer pinged me. Shall I maybe pass the ball to Melilly?

**Comment by vongomben** [comment]
I've updated te list to todays' events.

**Comment by MatthewJeffson** [comment]
@33Alison Hi, have you have any ideas, regarding the participation?
