### ISSUE TITLE
[Page Update] Collection page for Arduino

### ISSUE THREAD

**Issue by MatthewJeffson** [Seeed-Studio/wiki-documents#439]
## Overview
- We need your help to complete our collection page about Arduino 
## What we are trying to present:
1. What is Arduino
2. Arduino Software Introduction
a. [How to install Arduino Library](https://wiki.seeedstudio.com/How_to_install_Arduino_Library)
b. [How to Upload Code](https://wiki.seeedstudio.com/Upload_Code/)
c. [How to add Seeed Studio boards to Arduino IDE](https://wiki.seeedstudio.com/Seeed_Arduino_Boards/)
4. What is in the "Arduino" potion
a. Grove Shield for Arduino boards
b. Tutorials about using Arduino Software
c. Kit with Arduino Board
- Contents should be clear and logical, easy to understand(example)Collection Page for XIAO series: [INTRODUCTION](https://wiki.seeedstudio.com/SeeedStudio_XIAO_Series_Introduction/), [EXHIBITION](https://wiki.seeedstudio.com/xiao_topic_page/)
## How do we work together?
- **Leave a comment with your GitHub name below** as you accept this assignment and will complete the contents about what we are trying to present.
- The maintainer will assign and record you as our only contact for this assignment.
- You can first [Deploy this Wiki Platform Locally](https://wiki.seeedstudio.com/Deploy_Page_Locally/) (The entire source code .zip file is only 30 M)
- You will be invited as our **"Contributor"** once you ["Pull Request"](https://wiki.seeedstudio.com/Contribution-Guide/).
- The maintainer will review the PR and then merge.
## What do we offer?
We want to express our gratitude to our contributors by offering a range of rewards.  Depending on the difficulties(Tier 0/1/2/3), the time we expect(Days 1/3/7/15),  the actual  submission time and the actual submission contents, we will offer different levels of rewards.
1. We will provide our products or cash bonus to our contributors as a token of appreciation.
2. For those contributors who join our "Ranger Program"(announced soon), we offer even more exciting rewards, including access to our prototype products.
3. In addition, all contributors and their contributions will be acknowledged and showcased on our wiki platform.
## FAQ
- For any question, the contributor can directly commend here.

**Comment by aloysiousBenoy** [comment]
Hey @MatthewJeffson I think I can take up the first two sections of this task! Im not so sure of part 3 ie the 'What is in the "Arduino" potion'. Can you give me a better idea of what you're expecting here?

**Comment by MatthewJeffson** [comment]
Hi @aloysiousBenoy , as we had [in this page](https://wiki.seeedstudio.com/Arduino/#getting-started) 

![Image](https://github.com/Seeed-Studio/wiki-documents/assets/104187183/fdfb5bf1-bd83-42f3-9880-e3960d28ede8)

You can see that there are many products we made specifically for the Arduino board, including functional shields for Arduino board, basic and enhanced tutorials using Arduino board, and the kit with it. 

The purpose of part 3 is exhibiting the users that we have these things above, like we did in [XIAO exhibition page](https://wiki.seeedstudio.com/xiao_topic_page/#the-showcase-of-creative-creations). Just to make it be more easier to check. 

You can exhibit them in your way, the structure, the contents, whatever you have in mind. You can also discuss it with me using the Email, its in my GitHub profile :D

**Comment by chenxixiya** [comment]
@MatthewJeffson Hello Matthew, I have just created a PR about updating this~

**Comment by MatthewJeffson** [comment]
Thank you so much for the update!
