### ISSUE TITLE
[Page Update] Collection page for Raspberry Pi

### ISSUE THREAD

**Issue by MatthewJeffson** [Seeed-Studio/wiki-documents#440]
# This assignment has been successfully achieved 🎉

Thanks Corey and the wiki page is: https://wiki.seeedstudio.com/Raspberry_Pi/

## Overview
- We need your help to complete our collection page about Raspberry Pi
## What we are trying to present:
1. What is Raspberry Pi
2. How to use Raspberry Pi board(getting started)
3. What is in the "Raspberry Pi" potion
a. Raspberry Pi HAT(extension boards)
b. Kit with Raspberry Pi Board
- Contents should be clear and logical, easy to understand(example)Collection Page for XIAO series: [INTRODUCTION](https://wiki.seeedstudio.com/SeeedStudio_XIAO_Series_Introduction/), [EXHIBITION](https://wiki.seeedstudio.com/xiao_topic_page/)
## How do we work together?
- **Leave a comment with your GitHub name below** as you accept this assignment and will complete the contents about what we are trying to present.
- The maintainer will assign and record you as our only contact for this assignment.
- You can first [Deploy this Wiki Platform Locally](https://wiki.seeedstudio.com/Deploy_Page_Locally/) (The entire source code .zip file is only 30 M)
- You will be invited as our **"Contributor"** once you ["Pull Request"](https://wiki.seeedstudio.com/Contribution-Guide/).
- The maintainer will review the PR and then merge.
## What do we offer?
We want to express our gratitude to our contributors by offering a range of rewards.  Depending on the difficulties(Tier 0/1/2/3), the time we expect(Days 1/3/7/15),  the actual  submission time and the actual submission contents, we will offer different levels of rewards.
1. We will provide our products or cash bonus to our contributors as a token of appreciation.
2. For those contributors who join our "Ranger Program"(announced soon), we offer even more exciting rewards, including access to our prototype products.
3. In addition, all contributors and their contributions will be acknowledged and showcased on our wiki platform.
## FAQ
- For any question, the contributor can directly commend here.

**Comment by thompcd** [comment]
Hey @MatthewJeffson I'd like to help! I can take this one to get started

**Comment by MatthewJeffson** [comment]
Hi @thompcd Thank you so much! Glad to have you onboard!

**Comment by thompcd** [comment]
@MatthewJeffson where can I browse/find existing seeed assets?

For example, I see that the Jetson Nano included this asset, but I'm not sure how to search for a rpi equivalent. I am unable to find it in the wiki-documents repo and not sure of how to browse other published assets at files.seeedstudio.com

https://files.seeedstudio.com/wiki/wiki-platform/collection_page/NVIDIA_Jetson_collection_front.jpg

**Comment by MatthewJeffson** [comment]
Hello @thompcd All the assets files are stored on a server we holding which is the reason that images are from 'https://files.seeedstudio.com/wiki/..'... 
I have been reported such issue before and there some solutions to it:

1. You can leave me with your images here by comment.
2. You can also create a new repo to store the images.
3. And you can email me all the files you want to add.
I then will take care of the rest by uploading them to our server.

Sorry for the inconvent collaboration. I will try to improve it on our next phase.

**Comment by thompcd** [comment]
I just re-used existing assets to get around it. :) PR #538

**Comment by MatthewJeffson** [comment]
Hi! @thompcd I have seen it and really appreciate your work! The page looking good!
I will thank you for your contributions on our wiki platform:D
May I have you email address so we can discuss more?

**Comment by thompcd** [comment]
> Hi! @thompcd I have seen it and really appreciate your work! The page looking good!
> I will thank you for your contributions on our wiki platform:D
> May I have you email address so we can discuss more?

Corey.Dwayne.thompson@gmail.com
