### ISSUE TITLE
[Page Add][Basic function] Support Zephyr on Seeed Studio XIAO RP2040

### ISSUE THREAD

**Issue by MatthewJeffson** [Seeed-Studio/wiki-documents#447]
# This task has been converted as [Support Zephyr on SenseCAP Builder](https://github.com/orgs/Seeed-Studio/projects/6?pane=issue&itemId=38776394)

## Overview
- We need your help to support Zephyr on Seeed Studio XIAO RP2040 and leave us a wiki.
## What we are trying to present:
1. Product Overview(Product image)
2. Hardware Overview(pinout, IOs )
3. Prerequisites(What it requires for deploy)
4. Building method
5. Debug

reference: 
[XIAO SAMD21 for Zephyr](https://docs.zephyrproject.org/latest/boards/arm/seeeduino_xiao/doc/index.html)
[XIAO nRF52840 for Zephyr](https://docs.zephyrproject.org/latest/boards/arm/xiao_ble/doc/index.html)
[XIAO ESP32C3 for Zephyr](https://docs.zephyrproject.org/latest/boards/riscv/xiao_esp32c3/doc/index.html)
[XIAO ESP32S3 for Zephyr](https://docs.zephyrproject.org/latest/boards/xtensa/xiao_esp32s3/doc/index.html)
## How do we work together?
- **Leave a comment with your GitHub name below** as you accept this assignment and will complete the contents about what we are trying to present.
- The maintainer will assign and record you as our only contact for this assignment.
- You can first [Deploy this Wiki Platform Locally](https://wiki.seeedstudio.com/Deploy_Page_Locally/) (The entire source code .zip file is only 30 M)
- You will be invited as our **"Contributor"** once you ["Pull Request"](https://wiki.seeedstudio.com/Contribution-Guide/).
- The maintainer will review the PR and then merge.
## What do we offer?
We want to express our gratitude to our contributors by offering a range of rewards.  Depending on the difficulties(Tier 0/1/2/3), the time we expect(Days 1/3/7/15),  the actual  submission time and the actual submission contents, we will offer different levels of rewards.
1. We will provide our products or cash bonus to our contributors as a token of appreciation.
2. For those contributors who join our "Ranger Program"(announced soon), we offer even more exciting rewards, including access to our prototype products.
3. In addition, all contributors and their contributions will be acknowledged and showcased on our wiki platform.
## FAQ
- For any question, the contributor can directly commend here.
### I think I can complete the assignment, but I need more time?
- The timeframe here is based on our old experience, from people who has done it or something like that.
- However, **many projects will take much more time** under actual circumstances (including the main language of the contributors receiving the task and the actual creative difficulty)
- You can leave the time you need and a brief reason, we will evaluate the situation accordingly.

**Comment by Zachay-NAU** [comment]
Hello Matthew, this is Zach
I am familiar with XIAO series.
I think I am totally capable for this project.

**Comment by MatthewJeffson** [comment]
Hi! Zach!
Glad to have you the ranger onboard again!
I will prepare the things quickly and send you the related files.

**Comment by tianrking** [comment]
Hello Matthew, I would like to try this project. Can you assign it to me ? . Thx

**Comment by MatthewJeffson** [comment]
Hello @tianrking We have one which is supporting Zephyr on SenseCAP Builder. I think you will find it interesting:D
