### ISSUE TITLE
[Page Add][Basic function] Support more Grove sensors for SenseCAP S2110 Sensor Builder

### ISSUE THREAD

**Issue by MatthewJeffson** [Seeed-Studio/wiki-documents#448]
## Overview
- We need your help to support more Grove sensors for SenseCAP S2110 Sensor Builder.
## What we are trying to present:
1. Hardware Set Up
2. Software Set Up
3. Add the Sensor to SenseCAP S2110 Sensor Builder
4. Modbus Register Table
reference: 
[GitHub](https://github.com/Seeed-Studio/Seeed_Arduino_S2110)

Currently what we have supported:
[Grove - Temperature and Barometer Sensor (BMP280)](https://www.seeedstudio.com/Grove-Barometer-Sensor-BMP280.html)
[Grove - Oxygen Sensor (MIX8410)](https://www.seeedstudio.com/Grove-Oxygen-Sensor-MIX8410-p-4697.html)
[Grove - CO2 & Temperature & Humidity Sensor - SCD41](https://www.seeedstudio.com/Grove-CO2-Temperature-Humidity-Sensor-SCD41-p-5025.html)
[Grove - Sunlight Sensor - SI1151](https://www.seeedstudio.com/Grove-Sunlight-Sensor.html)
[Grove - Light Sensor v1.2 - LS06-S phototransistor](https://www.seeedstudio.com/Grove-Light-Sensor-v1-2-LS06-S-phototransistor.html)
[Grove - Flame Sensor](https://www.seeedstudio.com/Grove-Flame-Sensor.html)
[Grove - Gas Sensor(BME680)](https://www.seeedstudio.com/Grove-Temperature-Humidity-Pressure-and-Gas-Sensor-for-Arduino-BME680.html)
[Grove - Multichannel Gas Sensor v2](https://www.seeedstudio.com/Grove-Multichannel-Gas-Sensor-v2-p-4569.html?queryID=e92bca5d79e17a6d5bf1447be36e2ee2&objectID=4569&indexName=bazaar_retailer_products)
[Grove - TDS Sensor/Meter For Water Quality (Total Dissolved Solids)](https://www.seeedstudio.com/Grove-TDS-Sensor-p-4400.html?queryID=9f138cfc508f141092493577c1ca83bb&objectID=4400&indexName=bazaar_retailer_products)
[Grove - UV Sensor](https://www.seeedstudio.com/Grove-UV-Sensor.html?queryID=07ecb93f63b4035df7dfa9aea8b1e498&objectID=1345&indexName=bazaar_retailer_products)
[Grove - Ultrasonic Distance Sensor](https://www.seeedstudio.com/Grove-Ultrasonic-Distance-Sensor.html?queryID=ebe18a5e13611be3b60f176e7bfabde7&objectID=2281&indexName=bazaar_retailer_products)
[Grove - Turbidity Sensor](https://www.seeedstudio.com/Grove-Turbidity-Sensor-p-4399.html?queryID=42f9c89339bce9fbff617e5c8a0328eb&objectID=4399&indexName=bazaar_retailer_products)

## How do we work together?
- **Leave a comment with your GitHub name below** as you accept this assignment and will complete the contents about what we are trying to present.
- The maintainer will assign and record you as our only contact for this assignment.
- You can first [Deploy this Wiki Platform Locally](https://wiki.seeedstudio.com/Deploy_Page_Locally/) (The entire source code .zip file is only 30 M)
- You will be invited as our **"Contributor"** once you ["Pull Request"](https://wiki.seeedstudio.com/Contribution-Guide/).
- The maintainer will review the PR and then merge.
## What do we offer?
We want to express our gratitude to our contributors by offering a range of rewards.  Depending on the difficulties(Tier 0/1/2/3), the time we expect(Days 1/3/7/15),  the actual  submission time and the actual submission contents, we will offer different levels of rewards.
1. We will provide our products or cash bonus to our contributors as a token of appreciation.
2. For those contributors who join our "Ranger Program"(announced soon), we offer even more exciting rewards, including access to our prototype products.
3. In addition, all contributors and their contributions will be acknowledged and showcased on our wiki platform.
## FAQ
- For any question, the contributor can directly commend here.
### I think I can complete the assignment, but I need more time?
- The timeframe here is based on our old experience, from people who has done it or something like that.
- However, **many projects will take much more time** under actual circumstances (including the main language of the contributors receiving the task and the actual creative difficulty)
- You can leave the time you need and a brief reason, we will evaluate the situation accordingly.

**Comment by vongomben** [comment]
Hi!
I am super interested in helping building this part of the documentation,
which is also related to a product I am following.

Waiting for your feedback, thanks in advance

**Comment by MatthewJeffson** [comment]
Hi! Ranger!
Thanks for such quick respond! It is great to hear it related to your project:D
May I ask which sensor you would like to use? to add to the SenseCAP S2110 Sensor Builder support list?
Regards

**Comment by vongomben** [comment]
Hi Matthew. 
I'd rather work on the sensors in the [Hazard Response Mission Pack](https://github.com/Seeed-Studio/Hazard-Response-Mission-Pack), hence:
* [Grove - Lightning Sensor (AS3935)](https://www.seeedstudio.com/Grove-Lightning-Sensor-AS3935-p-5603.html)
* [Grove - D7S Vibration Sensor](https://www.seeedstudio.com/Grove-D7S-Vibration-Sensor-p-5701.html)
* [Grove - Laser PM2.5 Dust Sensor](https://www.seeedstudio.com/Grove-Laser-PM2-5-Sensor-HM3301.html)
* [Grove - Flame Sensor](https://www.seeedstudio.com/Grove-Flame-Sensor.html)
* [Grove - ORP Sensor Kit Pro](https://www.seeedstudio.com/Grove-ORP-Sensor-Kit-Pro-p-5570.html)

As I'm digging in the documentation, I understand that the task consists in 
1) adding a [*.hpp file in the sensor src folder](https://github.com/Seeed-Studio/Seeed_Arduino_S2110/tree/main/src/sensor) and 
2) assign a known register name and address to each sensor and sensor feature. 

I don't think I can do this within your timeframe, I prefer pass to somebody more prepared in C++ coding. 

But I'd gladly test and proofread the code / documentation if need.

**Comment by MatthewJeffson** [comment]
The timeframe here is based on our old experience, from people who has done it or something like that.

However, **many projects will take much more time** under actual circumstances (including the main language of the contributors receiving the task and the actual creative difficulty)

Different from the contributors. We have great trust in our rangers. If you feel that you require more time to complete the assignment, all we have are just gratitude and patience:D We are willing to accommodate your timeframe.

**Comment by vongomben** [comment]
Matthew, I really appreciate your words and availability, but since I'm the product owner of that kit, I cannot risk to be the very reason of possible delays. 

I need the products indeed, but I'd rather have somebody to work with and to look after with better C++ dev experience than me. 

I'll wait for some other ranger to pop by. 
I think there are other developers interested in the project. 
If nobody shows I'll review my decision.

What do you think?

**Comment by MatthewJeffson** [comment]
Okay, no problem at all.
Have a good day! :D

**Comment by the-confused-genius** [comment]
hey matthew, I would like to work on this task.

I have built libraries before, for other companies. Interested to build sensor libraries for senseCAP s2110.

Here is my email address if you like to connect, adnan503104@gmail.com

**Comment by MatthewJeffson** [comment]
@the-confused-genius Hello! Thank you for being interested in this assignment!
I will contact you for more information discuss:D
Regards,
Matthew

**Comment by MatthewJeffson** [comment]
This has been updated: https://wiki.seeedstudio.com/Build-LoRaWAN-Sensors-SenseCAP-XIAO-Controller-Data-Logger/
