### ISSUE TITLE
[Page Add] TinyML workshop

### ISSUE THREAD

**Issue by MatthewJeffson** [Seeed-Studio/wiki-documents#488]
# This assignment has been successfully achieved 🎉

Thanks Salman and the wiki page is: https://wiki.seeedstudio.com/tinyml_workshop_course_new/

## Overview
- We need your help to update the Wiki content about [TinyML workshop](https://wiki.seeedstudio.com/tinyml_workshop_course/).
- Make the workshop tinyML more easy and accessible
- The purpose is really How users can easily run the whole course using the wiki.
## What we are trying to present:
1. ([EdgeLab part](https://wiki.seeedstudio.com/tinyml_workshop_course/#1-edgelab))Using EdgeLab webpage to quickly run two models: Face Detection and Digital Meter Detection. -- This will make the participants instantly getting to know the features of XIAO ESP32S3 Sense (camera and TinyML capability)
2. ([Edge Impulse part from 2.1 to 2.2](https://wiki.seeedstudio.com/tinyml_workshop_course/#2-edge-impulse)) Using Arduino pre-trained libraries which are Speech Keyword Recognition and Fruit Identification to quickly get to know how to use Arduino IDE to achieve ML implementation.
3. ([Edge Impulse part 2.3](https://wiki.seeedstudio.com/tinyml_workshop_course/#23-edge-impulse-kws-application-in-xiao-esp32s3-sense)) Taking KWS application as an example to show the participants how to run the entire process of deploying the ML model using Edge Impulse.
4. The rest will be left to the participants who are familiar with Arduino and ML better and do their own DIY models.
## How do we work together?
- **Leave a comment with your GitHub name below** as you accept this assignment and will complete the contents about what we are trying to present.
- The maintainer will assign and record you as our only contact for this assignment.
- You can first [Deploy this Wiki Platform Locally](https://wiki.seeedstudio.com/Deploy_Page_Locally/) (The entire source code .zip file is only 30 M)
- You will be invited as our **"Contributor"** once you ["Pull Request"](https://wiki.seeedstudio.com/Contribution-Guide/).
- The maintainer will review the PR and then merge.
## What do we offer?
We want to express our gratitude to our contributors by offering a range of rewards.  Depending on the difficulties(Tier 0/1/2/3), the time we expect(Days 1/3/7/15),  the actual  submission time and the actual submission contents, we will offer different levels of rewards.
1. We will provide our products or cash bonus to our contributors as a token of appreciation.
2. For those contributors who join our "Ranger Program"(announced soon), we offer even more exciting rewards, including access to our prototype products.
3. In addition, all contributors and their contributions will be acknowledged and showcased on our wiki platform.
## FAQ
- For any question, the contributor can directly commend here.

**Comment by MatthewJeffson** [comment]
May I add some images here?
Sure:

[example.zip](https://github.com/Seeed-Studio/wiki-documents/files/12301524/example.zip)



![Image](https://github.com/Seeed-Studio/wiki-documents/assets/104187183/8ff98ff7-0051-4260-8e44-9e994f09a8b4)

**Comment by salmanfarisvp** [comment]
What about adding a new topic name "Workshop" smiler to Edge computing and network, below we can list the workshop docs? 

![Image](https://github.com/Seeed-Studio/wiki-documents/assets/11945360/515dd19e-0bb5-469e-8e5c-94fc07d68e0e)

**Comment by MatthewJeffson** [comment]
Yes, sure. We can create one and move the  "[TinyML](https://wiki.seeedstudio.com/tinyml_topic/)" topic page here as well.

**Comment by salmanfarisvp** [comment]
Shall we make a sub-page for each workshop, like 

TinyML Workshop
-> XIAO esp32s3 Sense 
    -> Key Word Spotting Workshop 
    -> Image recognition project workshop 

what do you think?

**Comment by MatthewJeffson** [comment]
Yes, for each workshop we should have one topic page, containing all the things that will be used in the workshop. Participates in the workshop simply click it and will see all the teaching contents of this workshop.

**Comment by salmanfarisvp** [comment]
@MatthewJeffson Could you please add two pages for adding materials? one for KWS and another one for image recognitions? I having issues while adding the page, Once you are done, I can add the contents. Thank You.

**Comment by MatthewJeffson** [comment]
Sure I will create one new category like sensing and computing there. Wait me a while

**Comment by MatthewJeffson** [comment]
Hi, I have added some files in the tinyml folder and added some contents at the "sidebar.js". And it will be available in 10 mins.

![Image](https://github.com/Seeed-Studio/wiki-documents/assets/104187183/fabbc8da-4988-47ad-a220-837b9ede2f4f)

**Comment by salmanfarisvp** [comment]
Thanks @MatthewJeffson . I will add the content now.
