### ISSUE TITLE
[Proposal] Inefficient Battery Utilization for Xiao ESP32-C3 in 4.2V-3.4V Range

### ISSUE THREAD

**Issue by AlexGolovko** [Seeed-Studio/wiki-documents#499]
**Issue Type:** Enhancement / Improvement

**Description:**
The Xiao ESP32-C3 is currently designed to operate within a voltage range of 4.2V to 3.4V. While this range technically covers the battery discharge curve, it results in suboptimal battery utilization. Operating the device down to 3.4V does not fully take advantage of the battery's capacity, potentially reducing the device's operational time on a single charge.

**Impact:**
- **Inefficient Power Utilization:** The current voltage range restricts the utilization of the battery's capacity, leading to reduced device runtime on a single charge.
- **User Experience:** Users may experience shorter device usage periods and more frequent battery replacements due to inefficient battery utilization.

**Suggested Solution:**
Expand the operational voltage range of the Xiao ESP32-C3 to a narrower and more effective range, such as 4.2V-3.7V. This would allow for better battery capacity utilization without compromising the battery's health and longevity.

**Steps to Reproduce:**
1. Charge the battery to full capacity.
2. Use the device until the battery voltage drops to 3.4V.
3. Observe the remaining battery capacity and device performance.

**Expected Behavior:**
The device should operate optimally within a narrower voltage range, resulting in increased battery capacity utilization and improved overall battery performance.

**Current Behavior:**
The device operates within a wide voltage range of 4.2V to 3.4V, leading to suboptimal battery utilization and potential reduction in device runtime.

**Additional Notes:**
- It's recommended to consult battery manufacturers' specifications and guidelines to determine the optimal voltage range for battery utilization.
- Care should be taken to balance battery capacity utilization and battery health considerations when adjusting the voltage range.
- Implementation of the suggested solution may require updates to the device firmware and documentation.

**Environment:**
- Device: Xiao ESP32-C3
- Firmware Version: [Insert firmware version]
- Battery Type: [Insert battery type and specifications]

**Labels:**
- Enhancement
- Battery Optimization
- Device Performance
- User Experience

**Priority:**
Consider marking this issue with a priority level based on its impact on device performance and user experience.

**Comment by MatthewJeffson** [comment]
Wow! Thank you so much for such technical advices!
Yet in our assessment, this will be required an additional IC to detect the battery voltage and then control whether the LDO is working. For the released XIAO series boards it will be temporarily not considered. 
In the future design of XIAO, we definitely will take a serious consideration about whether to add this function!
Thanks again! Really appreciate!

**Comment by MatthewJeffson** [comment]
Just one quick question: may I ask if you are interested on our Contributors Project? Simply check if [the assignments on the issue list](https://github.com/Seeed-Studio/wiki-documents/issues?page=2&q=is%3Aissue+is%3Aopen) are right for you. And if does, we can then discuss more about it.
