### ISSUE TITLE
directory mistake > ./scripts/reTerminal.sh

### ISSUE THREAD

**Issue by matsujirushi** [Seeed-Studio/wiki-documents#5]
Document is [here](https://wiki.seeedstudio.com/reTerminal/).

![image](https://user-images.githubusercontent.com/8079404/121829325-24230880-ccfd-11eb-8293-b9e48456188a.png)

Execution results.
![image](https://user-images.githubusercontent.com/8079404/121829374-44eb5e00-ccfd-11eb-9c5d-8167ba5c634b.png)

**Comment by Pillar1989** [comment]
@lakshanthad  pls

**Comment by lakshanthad** [comment]
@matsujirushi Can you switch to "main" branch and "git pull" ? The script has been moved from "mipi_dsi" branch to "master" branch.

**Comment by matsujirushi** [comment]
@lakshanthad ,
Sorry. Document is fine.

I was wrong.
![image](https://user-images.githubusercontent.com/8079404/122020938-2de16480-ce00-11eb-913f-55755d5ac9c7.png)
