### ISSUE TITLE
[Page Add][Enhanced Function] XIAO nRF52840 accesses Home Assistant and display temperature and humidity

### ISSUE THREAD

**Issue by MatthewJeffson** [Seeed-Studio/wiki-documents#514]
# This assignment has been successfully achieved 🎉

Thanks Bruno and the wiki page is: https://wiki.seeedstudio.com/XIAO-BLE-PDM-EI/

## Overview
- Connect [XIAO nRF52840](https://www.seeedstudio.com/Seeed-XIAO-BLE-nRF52840-p-5201.html) with a [Grove DHT20 Sensor](https://www.seeedstudio.com/Grove-Temperature-Humidity-Sensor-V2-0-DHT20-p-4967.html) to access Home Assistant
- Display the temperature and humidity on the Home Assistant
## Assignment acceptance
- Please check the "assignee" section before accepting to see if this has already been accepted.
- Please ensure that the **requested timeline** aligns with your workflow.
- Leave your **Github Name** below to indicate that you are willing to accept the job.
- If you are taking on the assignment **for the first time**, you may receive an invitation in your GitHub mail.
## Requirements(check list)
- Prove of video presentation
- Detailed operation procedure written in **Markdown file** with [wiki standards](https://files.seeedstudio.com/wiki/wiki-ranger/Standards_of_Product_ApplicationWiki_Upload.pdf)
- Upload wiki markdown file to GitHub repository with [guide & instructions](https://wiki.seeedstudio.com/Contribution-Guide/)
- List of products used
- Code files (".yaml" file that supports ESPHome, ".h" files, etc...)
## What do we offer?
We want to express our gratitude to our contributors by offering a range of rewards.  Depending on the difficulties(Tier 0/1/2/3), the time we expect(Days 1/3/7/15),  the actual  submission time and the actual submission contents, we will offer different levels of rewards.
1. We will provide our products or cash bonus to our contributors as a token of appreciation.
2. For those contributors who join our "Ranger Program"(announced soon), we offer even more exciting rewards, including access to our prototype products.
3. In addition, all contributors and their contributions will be acknowledged and showcased on our wiki platform.
## FAQ
For the ranger who accepts this assignment can have a conversation with your transition AE below

**Comment by feiticeir0** [comment]
feiticeir0

**Comment by MatthewJeffson** [comment]
Hello @feiticeir0  Welcome onboard! Do you currently have the XIAO nRF52840 board and essential devices right now?

**Comment by feiticeir0** [comment]
Hi Matthew. Thank you for the reply.

I thought I had that one, but I have the sense version. 

Is it ok? 

The Grove DHT20 I have.

Thank you

**Comment by MatthewJeffson** [comment]
Hi @feiticeir0 The Sense version is OK, as long as there are temperature and humidity value shown on the Home Assistant dashboard, connecting with the XIAO nRF52840 Sense.
May I have your email and add you as our repo contributor first? 
Then we can discuss more details, regarding the products or the bonus you want.

**Comment by feiticeir0** [comment]
Yes @MatthewJeffson !
Here's my Github email: feiticeir0@whatgeek.com.pt 
Thank you for the opportunity !

**Comment by MatthewJeffson** [comment]
Here we go, let's get started!:D

**Comment by feiticeir0** [comment]
@MatthewJeffson Thank you.

Where do I, after done, insert the video, code, etc... ?

**Comment by MatthewJeffson** [comment]
You can email them to me or you can create a GitHub repo to store like one of our ranger did at #334 
I will send you an email right now.

**Comment by MatthewJeffson** [comment]
Hi @feiticeir0 Bruno! I have received your email and will get back to you soon with the bonus discussion:D
FYI, this is @limengdu our AE and he will be in charged with the test.

Best Regards,
Matthew

**Comment by limengdu** [comment]
Thank you for your help, the program provided is currently tested and can be deployed successfully.

![Image](https://github.com/Seeed-Studio/wiki-documents/assets/37475446/42f9bff6-6626-46e4-a113-50c5d9af4328)

**Comment by feiticeir0** [comment]
> Thank you for your help, the program provided is currently tested and can be deployed successfully.
> 
> ![Image](https://user-images.githubusercontent.com/37475446/264906837-42f9bff6-6626-46e4-a113-50c5d9af4328.png)

Thank you @limengdu .

I'm still waiting on the sensor (grove DHT11) that should arrive during the next week. As soon as it arrives, I will implement the code with it. The code still needs some cleaning and clarification with comments. 

Thank you

Best regards

**Comment by feiticeir0** [comment]
Pull request done.

**Comment by MatthewJeffson** [comment]
Hello! @feiticeir0 I have updated the contents. Once the PR test passed, the PR will be merged:D
Thank you so much for doing this!
