### ISSUE TITLE
[Page Add][Enhanced Function] Make LoRaWAN protocol stack adapted to SenseCAP Indicator, allowed communicating with LoRaWAN network

### ISSUE THREAD

**Issue by MatthewJeffson** [Seeed-Studio/wiki-documents#517]
## Overview
- Adapt LoRaWAN protocol stack to [SenseCAP Indicator(ESP32)](https://www.seeedstudio.com/SenseCAP-Indicator-D1-p-5643.html) and allow it can communicate with LoRaWAN network(Helium or others).
## Assignment acceptance
- Please check the "assignee" section before accepting to see if this has already been accepted.
- Please ensure that the **requested timeline** aligns with your workflow.
- Leave your **Github Name** below to indicate that you are willing to accept the job.
- If you are taking on the assignment **for the first time**, you may receive an invitation in your GitHub mail.
## Requirements(check list)
- Prove of video presentation
- Detailed operation procedure written in **Markdown file** with [wiki standards](https://files.seeedstudio.com/wiki/wiki-ranger/Standards_of_Product_ApplicationWiki_Upload.pdf)
- Upload wiki markdown file to GitHub repository with [guide & instructions](https://wiki.seeedstudio.com/Contribution-Guide/)
- List of products used
- Code files that complete the program
## What do we offer?
We want to express our gratitude to our contributors by offering a range of rewards.  Depending on the difficulties(Tier 0/1/2/3), the time we expect(Days 1/3/7/15),  the actual  submission time and the actual submission contents, we will offer different levels of rewards.
1. We will provide our products or cash bonus to our contributors as a token of appreciation.
2. For those contributors who join our "Ranger Program"(announced soon), we offer even more exciting rewards, including access to our prototype products.
3. In addition, all contributors and their contributions will be acknowledged and showcased on our wiki platform.
## FAQ
For the ranger who accepts this assignment can have a conversation with your transition AE below

**Comment by salmanfarisvp** [comment]
@MatthewJeffson Is it similar to the LoRa WAN Integration we did on XIAO and Grove module?

**Comment by Love4yzp** [comment]
> @MatthewJeffson Is it similar to the LoRa WAN Integration we did on XIAO and Grove module?

Dude, that's not a Grove system with uart, that's programming on the ESP32 to drive the SX126. -> https://github.com/Seeed-Solution/indicator_lora_commu/blob/master/Indicator/components/lora/sx126x_sensecap_board.c

**Comment by salmanfarisvp** [comment]
Thanks for the info @Love4yzp , I meant is it similar to the assignment on the XIAO LoRa assignment we did in the past?

**Comment by MatthewJeffson** [comment]
Hi @salmanfarisvp I'm sorry for the late responses. And indeed it is like @Love4yzp said it requires using [SenseCAP Indicator D1L](https://www.seeedstudio.com/SenseCAP-Indicator-D1L-p-5646.html) or D1 Pro to achieve this project.
Hence, it will be more challenged and thus the difficulty is set as "Tier 2" instead of "Tier 1" to "XIAO LoRa" assignment.
Hope this can make it clear.
Best Regards,
Matthew

**Comment by MatthewJeffson** [comment]
Hi @salmanfarisvp Salman! FYI, if you are interested in achieving this project, I can send you the related product and provide the needed documentation for you. Just let me know by then:D
Matthew

**Comment by salmanfarisvp** [comment]
Hi @MatthewJeffson , Thank you and I would like to work on it. (I'm already getting one, so need to send)

**Comment by MatthewJeffson** [comment]
@salmanfarisvp That is really great! Thank you for taking it! I really appreciate it! 
Then I will leave you to that. Looking forward your work:D
Best Regards,
Matthew

**Comment by MatthewJeffson** [comment]
This assignment has been achieved: #889
