### ISSUE TITLE
[Page Update][Enhanced Function] Support Arduino programming with the SenseCAP Indicator(ESP32 chip)

### ISSUE THREAD

**Issue by MatthewJeffson** [Seeed-Studio/wiki-documents#518]
# This assignment has been successfully achieved 🎉 

- Thanks Hendra and the wiki page is: https://wiki.seeedstudio.com/SenseCAP_Indicator_ESP32_Arduino/
- We are still looking for someone who can [improve this assignment](https://wiki.seeedstudio.com/SenseCAP_Indicator_ESP32_Arduino/#whats-more).

## Overview
- Develop to support programming [SenseCAP Indicator(ESP32)](https://www.seeedstudio.com/SenseCAP-Indicator-D1-p-5643.html) with Arduino and design a touchable UI interface.
- Ensure that the screen slides smoothly and the fps does not decrease

reference: [Develop with ESP32S3 chip](https://wiki.seeedstudio.com/SenseCAP_Indicator_ESP32_4_inch_Touch_Screen/)
## Assignment acceptance
- Please check the "assignee" section before accepting to see if this has already been accepted.
- Please ensure that the **requested timeline** aligns with your workflow.
- Leave your **Github Name** below to indicate that you are willing to accept the job.
- If you are taking on the assignment **for the first time**, you may receive an invitation in your GitHub mail.
## Requirements(check list)
- Prove of video presentation
- Detailed operation procedure written in **Markdown file** with [wiki standards](https://files.seeedstudio.com/wiki/wiki-ranger/Standards_of_Product_ApplicationWiki_Upload.pdf)
- Upload wiki markdown file to GitHub repository with [guide & instructions](https://wiki.seeedstudio.com/Contribution-Guide/)
- List of products used
- Code files that complete the program
## What do we offer?
We want to express our gratitude to our contributors by offering a range of rewards.  Depending on the difficulties(Tier 0/1/2/3), the time we expect(Days 1/3/7/15),  the actual  submission time and the actual submission contents, we will offer different levels of rewards.
1. We will provide our products or cash bonus to our contributors as a token of appreciation.
2. For those contributors who join our "Ranger Program"(announced soon), we offer even more exciting rewards, including access to our prototype products.
3. In addition, all contributors and their contributions will be acknowledged and showcased on our wiki platform.
## FAQ
For the ranger who accepts this assignment can have a conversation with your transition AE below

**Comment by chalei** [comment]
hello @MatthewJeffson I happen to have the Sensecap Indicator. Can I take this one. I just need one information about the screen. what is the LCD and touchscreen module is use for the sensecap indicator?

**Comment by MatthewJeffson** [comment]
Hi @chalei That sounds great! And here are the information for SenseCAP Indicator:

RGB: 480*480
Touch IC: FT6336U ( I2C)
Display IC: ST7701S

Please ask me if you need anything else.
Let's get started! :D

**Comment by MatthewJeffson** [comment]
BTW, are you planning using LVGL to design UI? If so, we have a [wiki](http://localhost:3000/SenseCAP_Indicator_How_to_Create_your_own_UI/) that might be helpful.

**Comment by chalei** [comment]
Thank You Matthew, Yes, I will probably gonna use the Arduino version of LVGL for this. But I will test the screen 1st using the arduino GFX Library.
Thanks for sharing the Information about the LCD also, I already check the schematic  of the sensecap indicator but couldn't find the info about the screen.

Btw my sensecap indicator is the prototype version given by mengdu before release, it has all the feature except Lora part. Does the lora for the sensecap indicator connect via SPI or UART like the e5 module?

**Comment by MatthewJeffson** [comment]
Hi, Hendra, the LoRa is controlled with UART communication

Here is the diagram and hope it can be helpful:

> WIFI(BLE) <-> ESP32S3 <-UART-> RP2040 <-> Sensors(analog、I2C）


![Image](https://github.com/Seeed-Studio/wiki-documents/assets/104187183/352bf59f-64fa-488e-91b3-6db4a669e76b)

**Comment by chalei** [comment]
Hello matthew sorry for the late update. It turns out the task is quite challenging for me. But tonight I have successfully run an arduino library on the sensecap indicator. will testing out other example soon after

https://www.youtube.com/watch?v=Ec0dE_Nf2Uw

**Comment by MatthewJeffson** [comment]
Wow! That looks amazing! It is a really good presentation!
Can't wait to see the rest of it.:D
Best Regards,
Matthew

**Comment by chalei** [comment]
Hello @MatthewJeffson I Already created a pull request for this task #620 

Let me know if it still missing something.
Sorry if it took longer than expected

**Comment by MatthewJeffson** [comment]
Hello! @chalei  Thanks! I will take a look:D
