### ISSUE TITLE
[Page Add][Industrial Function] Deploy industrial software Ignition into reTerminal DM

### ISSUE THREAD

**Issue by MatthewJeffson** [Seeed-Studio/wiki-documents#520]
## Overview
- Deploy [Ignition](https://inductiveautomation.com/ignition/) into [reTerminal DM](https://www.seeedstudio.com/reTerminal-DM-p-5616.html) to achieve real-time data acquisition from the production process and its management and optimization.
## Assignment acceptance
- Please check the "assignee" section before accepting to see if this has already been accepted.
- Please ensure that the **requested timeline** aligns with your workflow.
- Leave your **Github Name** below to indicate that you are willing to accept the job.
- If you are taking on the assignment **for the first time**, you may receive an invitation in your GitHub mail.
## Requirements(check list)
- Prove of video presentation
- Detailed operation procedure written in **Markdown file** with [wiki standards](https://files.seeedstudio.com/wiki/wiki-ranger/Standards_of_Product_ApplicationWiki_Upload.pdf)
- Upload wiki markdown file to GitHub repository with [guide & instructions](https://wiki.seeedstudio.com/Contribution-Guide/)
- List of products used
- Code files that complete the program
## What do we offer?
We want to express our gratitude to our contributors by offering a range of rewards.  Depending on the difficulties(Tier 0/1/2/3), the time we expect(Days 1/3/7/15),  the actual  submission time and the actual submission contents, we will offer different levels of rewards.
1. We will provide our products or cash bonus to our contributors as a token of appreciation.
2. For those contributors who join our "Ranger Program"(announced soon), we offer even more exciting rewards, including access to our prototype products.
3. In addition, all contributors and their contributions will be acknowledged and showcased on our wiki platform.
## FAQ
For the ranger who accepts this assignment can have a conversation with your transition AE below

**Comment by thompcd** [comment]
Am I correct that this request is to install [Ignition Edge](https://inductiveautomation.com/ignition/edge) on the display and not the full Ignition SCADA software? I assume so but want to double check. 

Are there ideas on what the demo should entail once installed, or this up to the contributor to decide?

**Comment by MatthewJeffson** [comment]
Hi! @thompcd Nice to see you again!
Regarding the [Ignition Edge](https://inductiveautomation.com/ignition/edge) development, we pretty sure the reTerminal DM can be used in IIoT or as a HMI with multiple filed devices. This is the reason we want the Ignition Edge to be installed in the DM. The demo (calling devices or something) will be up to the contributor.

Meanwhile, would you mind also check if the other three functions here are suitable for the DM, from your professional perspective? It would be a huge help for us.



![Image](https://github.com/Seeed-Studio/wiki-documents/assets/104187183/1125cacb-66d9-4641-a8a1-f245a650b47d)

**Comment by thompcd** [comment]
I've created some reference diagrams of some of the Ignition Edge configurations available with Seeed hardware. My initial demo will be the most simple use case, covering the panel builder and an edge gateway

![Edge Sync w- Compute](https://github.com/Seeed-Studio/wiki-documents/assets/20342605/029362f4-746a-4377-bf4c-eb77ed042301)
![Edge Sync](https://github.com/Seeed-Studio/wiki-documents/assets/20342605/74ae52a7-2434-4fe7-96b4-79c417f5c426)
![Edge Panel](https://github.com/Seeed-Studio/wiki-documents/assets/20342605/2a160c9c-a7c3-488f-8803-ea15d9e0891b)

*re-uploaded, some layers did not export in original

**Comment by MatthewJeffson** [comment]
Hi @thompcd Thank you so much for providing the additional information here!
The visuals here look great!

**Comment by thompcd** [comment]
I've got a 'hello world' up and running for this in my repo with it documented but have not yet formatted it for seeed wiki standards.

https://github.com/tulsasoftware/reterminal-ignition-edge-panel

**Comment by MatthewJeffson** [comment]
Wow, it's just a privilege to watch your work!

**Comment by MatthewJeffson** [comment]
Closed for temporary
