### ISSUE TITLE
[Page Add][Industrial Function] Deploy industrial software Ignition into EdgeBox-rpi-200

### ISSUE THREAD

**Issue by MatthewJeffson** [Seeed-Studio/wiki-documents#521]
## Overview
- Deploy industrial software [Ignition](https://inductiveautomation.com/ignition/) into [EdgeBox-RPI-200](https://www.seeedstudio.com/EdgeBox-RPi-200-CM4104016-p-5486.html) to achieve real-time data acquisition from the production process and its management and optimization.
## Assignment acceptance
- Please check the "assignee" section before accepting to see if this has already been accepted.
- Please ensure that the **requested timeline** aligns with your workflow.
- Leave your **Github Name** below to indicate that you are willing to accept the job.
- If you are taking on the assignment **for the first time**, you may receive an invitation in your GitHub mail.
## Requirements(check list)
- Prove of video presentation
- Detailed operation procedure written in **Markdown file** with [wiki standards](https://files.seeedstudio.com/wiki/wiki-ranger/Standards_of_Product_ApplicationWiki_Upload.pdf)
- Upload wiki markdown file to GitHub repository with [guide & instructions](https://wiki.seeedstudio.com/Contribution-Guide/)
- List of products used
- Code files that complete the program
## What do we offer?
We want to express our gratitude to our contributors by offering a range of rewards.  Depending on the difficulties(Tier 0/1/2/3), the time we expect(Days 1/3/7/15),  the actual  submission time and the actual submission contents, we will offer different levels of rewards.
1. We will provide our products or cash bonus to our contributors as a token of appreciation.
2. For those contributors who join our "Ranger Program"(announced soon), we offer even more exciting rewards, including access to our prototype products.
3. In addition, all contributors and their contributions will be acknowledged and showcased on our wiki platform.
## FAQ
For the ranger who accepts this assignment can have a conversation with your transition AE below

**Comment by MatthewJeffson** [comment]
Hi @thompcd I will deliver the products to you as soon as possible.:D

**Comment by thompcd** [comment]
I will have a PR for this within a few days of the approval of PR #520. 

A lot of the content for the edge box setup will be shared between the products, so I am trying to prevent duplicate work

**Comment by thompcd** [comment]
Created PR #698 

Tested on clean install of 32-bit SenseCraft Edge OS and 64-bit RPi OS.
Re-used existing images from ReTerminal Ignition Edge posts, you shouldn't need to upload any new images

**Comment by MatthewJeffson** [comment]
Closed for temporary
