### ISSUE TITLE
[Page Add][Basic function] Connect with XIAO series with Grove - Wio-e5 to upload the data to Helium Cloud

### ISSUE THREAD

**Issue by MatthewJeffson** [Seeed-Studio/wiki-documents#530]
# This assignment has been successfully achieved 🎉

The wiki page is: https://wiki.seeedstudio.com/SenseCAP_Indicator_Application_LoRaWAN/

## Overview
- We need your help to connect with XIAO series with Grove - Wio-e5 to upload the data to Helium Cloud.
## What we are trying to present:
1. Step by step show how to make all the XIAO series with Grove - Wio-e5 connection work
2. Upload the data to Helium Cloud
reference: 
- [XIAO SAMD21 connect with Grove - Wio-e5 to upload the data to TTN Cloud](https://wiki.seeedstudio.com/Grove_LoRa_E5_New_Version/)
- [SenseCAP K1100(wio terminal) connecting Helium](https://wiki.seeedstudio.com/Connecting-to-Helium/)
## How do we work together?
- **Leave a comment with your GitHub name below** as you accept this assignment and will complete the contents about what we are trying to present.
- The maintainer will assign and record you as our only contact for this assignment.
- You can first [Deploy this Wiki Platform Locally](https://wiki.seeedstudio.com/Deploy_Page_Locally/) (The entire source code .zip file is only 30 M)
- You will be invited as our **"Contributor"** once you ["Pull Request"](https://wiki.seeedstudio.com/Contribution-Guide/).
- The maintainer will review the PR and then merge.
## What do we offer?
We want to express our gratitude to our contributors by offering a range of rewards.  Depending on the difficulties(Tier 0/1/2/3), the time we expect(Days 1/3/7/15),  the actual  submission time and the actual submission contents, we will offer different levels of rewards.
1. We will provide our products or cash bonus to our contributors as a token of appreciation.
2. For those contributors who join our "Ranger Program"(announced soon), we offer even more exciting rewards, including access to our prototype products.
3. In addition, all contributors and their contributions will be acknowledged and showcased on our wiki platform.
## FAQ
- For any question, the contributor can directly commend here.
### I think I can complete the assignment, but I need more time?
- The timeframe here is based on our old experience, from people who has done it or something like that.
- However, **many projects will take much more time** under actual circumstances (including the main language of the contributors receiving the task and the actual creative difficulty)
- You can leave the time you need and a brief reason, we will evaluate the situation accordingly.

**Comment by Zachay-NAU** [comment]
Hello Matthew, this is Zach
I am familiar with XIAO series.
I think I am totally capable for this project.

**Comment by MatthewJeffson** [comment]
Hi! Zach!
Glad to have you the ranger onboard again!
I will prepare the things quickly and send you the related files.

**Comment by waveform06** [comment]
If anyone needs any help on the Helium side tag me https://github.com/waveform06
Or I work for Helium and Im waveformiot on the Helium, SenseCAP and Seeed Discords.

**Comment by illperipherals** [comment]
I believe a lot of this was knocked out with the SEEED/Helium E5/wio "Barrel" kits. 

I do not work for Helium, but I have a bit of experience in the area.
I would be interested in more information here, please.

**Comment by salmanfarisvp** [comment]
Hi @MatthewJeffson , I am also interested in this project.

**Comment by MatthewJeffson** [comment]
@waveform06 Thank you so much for providing the help!
And yes @illperipherals , this project can be used [SenseCAP K1100(wio terminal D21) connecting Helium](https://wiki.seeedstudio.com/Connecting-to-Helium/) as a reference. I will add it in the overview as well.

**Comment by MatthewJeffson** [comment]
Hi @Zachay-NAU @salmanfarisvp ! Since the XIAO series include all five XIAO. Maybe we can separate this assignment based on the products what you guys have on hand. 
I will contact you guys for more details.:D

**Comment by salmanfarisvp** [comment]
Sure @MatthewJeffson and I have XIAO nRF52840 Sense, XIAO SAMD, and XIAO ESP32S3 Sense along with the WIO-E5 Grove module. I can start right away.

**Comment by MatthewJeffson** [comment]
@salmanfarisvp Wow! That's really nice! There are sensors on XIAO nRF52840 Sense and XIAO ESP32S3 Sense where both of them can be deployed ML models. I was thinking, would it be better to make the project enhanced which makes the uploaded data as ML model sensing data? :D
reference:
[Motion Recognition with XIAO nRF52840](https://wiki.seeedstudio.com/XIAOEI/)
[Image classification with XIAO ESP32S3 Sense](https://wiki.seeedstudio.com/tinyml_course_Image_classification_project/)
Regarding XIAO SAMD21, connecting with a Grove sensor I think will be fine?

What do you think?

**Comment by salmanfarisvp** [comment]
@MatthewJeffson That's good. We can make a basic sketch first to send a sample string or number, then on top of that, we can make project guides as you mentioned - like sending inference results over helium to the dashboard. 

Also, we can connect the XIAO with a Grove XIAO Sheild and expansion board with OLED with that we can easily connect.

**Comment by MatthewJeffson** [comment]
@salmanfarisvp That sounds a great plan.

**Comment by andresoliva** [comment]
Hello. I have XIAO ESP32S3 , Arduino nano 33 BLE sense and WIO-E5 Grove module. If possible, I would love to work with Arduino nano 33 BLE sense because if the board we are most using for our animal behaivour research. I will be waiting for the assignment. 

Andres

**Comment by MatthewJeffson** [comment]
@andresoliva I can see you have launched and updated the library of [Grove - Wio-e5 for ESP32S3 board](https://github.com/andresoliva/LoRa-E5). Nicely done! Just want to be grateful for your work. I will try to find it way to present it.:D I can't access my Linkedin account right now so I am saying here.:D
Best regards,
Matthew

**Comment by andresoliva** [comment]
@MatthewJeffson Thank you!!!!. Great, i will be waiting then. Tell me if you need anything more. I hope you have a nice week !!.

**Comment by salmanfarisvp** [comment]
Successfully connected to helium with E5 grove, will add the docs soon. 

![Image](https://github.com/Seeed-Studio/wiki-documents/assets/11945360/a022c602-3fb5-49be-bd48-58c1e6102085)

**Comment by MatthewJeffson** [comment]
@salmanfarisvp That is great news! Can't wait to see that :D

**Comment by salmanfarisvp** [comment]
@MatthewJeffson PR is ready to review https://github.com/Seeed-Studio/wiki-documents/pull/568

**Comment by MatthewJeffson** [comment]
Hi @salmanfarisvp Thanks for the update! I can see you no only wrote about the Helium, but also the TTN and P2P.
That is really amazed! Will test as soon as possible.
Best Regards,
Matthew

**Comment by salmanfarisvp** [comment]
@MatthewJeffson I only made the helium one. The TTN and P2P were already there but I made them on separate pages for clarity. I fully tested the helium and changed code from TTN, so that user can use any EUI as per their choice.

**Comment by MatthewJeffson** [comment]
@salmanfarisvp Oh, thanks for clarifying. Nice work!:D

**Comment by salmanfarisvp** [comment]
@MatthewJeffson Anything pending now?

**Comment by MatthewJeffson** [comment]
Hi @salmanfarisvp We want to ensure every XIAO board is compatible with [Grove - Wio-E5 Helium Demo](https://wiki.seeedstudio.com/Grove_Wio_E5_Helium_Demo/)
And like we discussed above, is it possible using sensors on XIAO nRF52840 Sense and XIAO ESP32S3 Sense and applying ML to send inference results over helium to the dashboard?

> There are sensors on XIAO nRF52840 Sense and XIAO ESP32S3 Sense where both of them can be deployed ML models. I was thinking, would it be better to make the project enhanced which makes the uploaded data as ML model sensing data? :D

Regards

**Comment by salmanfarisvp** [comment]
Sure, @MatthewJeffson I can work on a project and document here, on it.

**Comment by salmanfarisvp** [comment]
@MatthewJeffson , Added the project details at https://github.com/Seeed-Studio/wiki-documents/pull/633 .  I was out of helium credits and it took time to add the credits.
