### ISSUE TITLE
Directory Error in Flashing Orin NX on A603 Instructions

### ISSUE THREAD

**Issue by bretaw** [Seeed-Studio/wiki-documents#595]
In https://wiki.seeedstudio.com/reComputer_A603_Flash_System/, Step 5 ("sudo tools/l4t_create_default_user.sh ...) doesn't work because after following previous steps, the user is in the wrong directory. A "cd Linux_for_Tegra" needs to be executed first. However, that statement then needs to be removed in Step 6.

**Comment by MatthewJeffson** [comment]
Hello! @bretaw Thanks for pointing it out!
I will inform the PM and change it:D
