### ISSUE TITLE
[ESPHome Development] ESPHome Support on Seeed Studio XIAO ESP32C3

### ISSUE THREAD

**Issue by MatthewJeffson** [Seeed-Studio/wiki-documents#603]
# This assignment has been successfully achieved 🎉

Thanks Zachay and the wiki page is: https://wiki.seeedstudio.com/XIAO-ESP32C3-for-ESPHome-Support/

## Overview
- We need your help to support all the ports XIAO ESP32C3 using ESPHome.
## What we are trying to present:
1. Present the code to support all the ports(digital, analog, SPI, IIC) on XIAO ESP32C3 using ESPHome, with selected Grove sensors or display or other modules. 
2. Present the code to show the camera usage and digital microphone using ESPHome.
reference:
 [XIAO ESP32C3 introduction page](https://wiki.seeedstudio.com/XIAO_ESP32C3_Getting_Started/)
 [HA official](https://github.com/esphome/esphome) 
 [ESPHome Core Configuration](https://www.esphome.io/components/esphome.html)
## How do we work together?
- **Leave a comment with your GitHub name below** as you accept this assignment and will complete the contents about what we are trying to manage.
- The assignees can discuss here with comments or any social communication.
- Once the assignment has been completed, we might need video of the presence and the code as well.
- There are no needs for additional wiki contents like the original Contributor Program requirements.
## What do we offer?
We want to express our gratitude to our contributors by offering a range of rewards.  Depending on the difficulties(Tier 0/1/2/3), the time we expect(Days 1/3/7/15),  the actual  submission time and the actual submission contents, we will offer different levels of rewards.
1. We will provide our products or cash bonus to our contributors as a token of appreciation.
2. For those contributors who join our "Ranger Program"(announced soon), we offer even more exciting rewards, including access to our prototype products.
3. In addition, all contributors and their contributions will be acknowledged and showcased on our wiki platform.
## FAQ
- For any question, the contributor can directly commend here.
### I think I can complete the assignment, but I need more time?
- The timeframe here is based on our old experience, from people who has done it or something like that.
- However, **many projects will take much more time** under actual circumstances (including the main language of the contributors receiving the task and the actual creative difficulty)
- You can leave the time you need and a brief reason, we will evaluate the situation accordingly.

**Comment by Zachay-NAU** [comment]
Hi Matthew, this is Zachary. I am compatible for the project and I have everything for it now.
Hope I can have the opportunity to solve this problem.

**Comment by MatthewJeffson** [comment]
Thank you! Zachary. It is great to have you!

**Comment by Zachay-NAU** [comment]
Done! 

[Projects](https://github.com/Zachay-NAU/ESPHome-Support-on-Seeed-Studio-XIAO-ESP32C3/blob/main/README.md)
[Video](https://www.youtube.com/watch?v=_umeHE_G2PE)

BEST,

ZAC

**Comment by MatthewJeffson** [comment]
Really nice! 
Thank you Zachay!
Matthew
