### ISSUE TITLE
Seeed Studio XIAO nRF52840 on Amazon Sidewalk - no west.yml

### ISSUE THREAD

**Issue by rabarar** [Seeed-Studio/wiki-documents#617]
**Is your feature request related to a problem? Please describe.**
The tutorial  at ( https://wiki.seeedstudio.com/xiao-ble-sidewalk/) doesn't work as there is not a `west.yml` file in the `sidewalk` distribution. Running:

```
west config manifest.path sidewalk
west update
```

will fail as there is not manifest file in the `sidewalk directory`

**Describe the solution you'd like**
make the tutorial work! as the current repo stands, one can't build a project from the command line using `zephyr`

**Describe alternatives you've considered**

**Additional context**

**Comment by MatthewJeffson** [comment]
> west config manifest.path sidewalk
> west update

Hi, this is not executed under the `sidewalk directory`, and the command should be executed using the terminal of the nRF Desktop.
The default should be: C:\ncs\v2.3.0

Hope this can be helpful.

**Comment by rabarar** [comment]
So, I am not executing the command in the sidewalk directory. I have the nRF Desktop for the Nordic DK - and it works… here’s their directions that work for the Nordic Board:


https://nrfconnect.github.io/sdk-sidewalk/setting_up_sidewalk_environment/setting_up_sdk.html￼

**Comment by rabarar** [comment]
Um, your docs are wrong…. You may want to review and update your docs…….On Sep 25, 2023, at 9:32 PM, Matthew ***@***.***> wrote:﻿
Closed #617 as completed.

**Comment by MatthewJeffson** [comment]
Hi @rabarar 
The contents have been reviewed by AWS official. Thank you for the issue presenting here, but sorry regarding the contents here we have to wait for AWS official to inform us.:D
Best Regards,
Matthew
