### ISSUE TITLE
KiCAD Symbol Bug

### ISSUE THREAD

**Issue by BastelBaus** [Seeed-Studio/wiki-documents#621]
In [ESP32S (Sense) KiCad library](https://files.seeedstudio.com/wiki/SeeedStudio-XIAO-ESP32S3/res/Seeeduino-xiao-ESP32S3-KiCAD-Library.zip), there is a pin named "(name "PB09_A7_D7_RX" (effects (font (size 1.016 1.016))))" but this is not an analog PIN and A7 is not defined. Same for " (name "PB08_A6_D6_TX" (effects (font (size 1.016 1.016))))" with A6. 

Luckily I had only hand wires I could easily re-wire :-). Nevertheless, really cool product!

BR,
BastelBaus

**Comment by MatthewJeffson** [comment]
Thanks for interesting our products and thank you for your kind words!
The file has been changed:D
Best Regards,
Matthew
