### ISSUE TITLE
[ReTerminal DM] Bluetooth not working

### ISSUE THREAD

**Issue by ClovisCorde** [Seeed-Studio/wiki-documents#641]
Hello, I have a problem with my reTerminal and I can’t find solutions online.
I had the problem with the reTerminal powering up a blank screen after the first boot. 
So I flashed the 32 bit Raspbian-reTerminal image by following the instructions from : https://wiki.seeedstudio.com/reTerminal-FAQ/#q2-how-can-i-flash-raspberry-pi-os-which-is-originally-shipped-with-reterminal 
The reTerminal is now working great except for bluetooth.
Indeed, after the first boot I type ```sudo systemctl status bluetooth``` and I get this result :

```
bluetooth.service - Bluetooth service
     Loaded: loaded (/lib/systemd/system/bluetooth.service; enabled; vendor preset: enabled)
     Active: inactive (dead)
       Docs: man:bluetoothd(8)

Sep 20 16:35:27 tgf systemd[1]: Condition check resulted in Bluetooth service being skipped.
Sep 20 16:36:56 tgf systemd[1]: Condition check resulted in Bluetooth service being skipped.
```
So I typed ```sudo modprobe btusb``` and then started bluetooth manually, when I type ```sudo systemctl status bluetooth``` I now get this result : 
```
bluetooth.service - Bluetooth service
     Loaded: loaded (/lib/systemd/system/bluetooth.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2023-09-20 16:37:18 BST; 1s ago
       Docs: man:bluetoothd(8)
   Main PID: 1569 (bluetoothd)
     Status: "Running"
      Tasks: 1 (limit: 4164)
        CPU: 49ms
     CGroup: /system.slice/bluetooth.service
             └─1569 /usr/libexec/bluetooth/bluetoothd

Sep 20 16:37:18 tgf systemd[1]: Starting Bluetooth service...
Sep 20 16:37:18 tgf bluetoothd[1569]: Bluetooth daemon 5.55
Sep 20 16:37:18 tgf systemd[1]: Started Bluetooth service.
Sep 20 16:37:18 tgf bluetoothd[1569]: Starting SDP server
Sep 20 16:37:18 tgf bluetoothd[1569]: Bluetooth management interface 1.21 initialized
```
Now my problem is that when I type “hcitool dev” there is no device.
Also, I saw online that it could be a problem with the UART and when I type “sudo systemctl status hciuart.service” I get this result :
```
     hciuart.service - Configure Bluetooth Modems connected by UART
     Loaded: loaded (/lib/systemd/system/hciuart.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2023-09-20 16:35:49 BST; 4min 12s ago
    Process: 557 ExecStart=/usr/bin/btuart (code=exited, status=1/FAILURE)
        CPU: 68ms

Sep 20 16:35:19 tgf systemd[1]: Starting Configure Bluetooth Modems connected by UART...
Sep 20 16:35:49 tgf btuart[625]: Initialization timed out.
Sep 20 16:35:49 tgf btuart[625]: bcm43xx_init
Sep 20 16:35:49 tgf systemd[1]: hciuart.service: Control process exited, code=exited, status=1/FAILURE
Sep 20 16:35:49 tgf systemd[1]: hciuart.service: Failed with result 'exit-code'.
Sep 20 16:35:49 tgf systemd[1]: Failed to start Configure Bluetooth Modems connected by UART.
```
Does anyone have a solution for this? My goal is to be able to scan bluetooth devices around the reTerminal. Thanks

**Comment by ClovisCorde** [comment]
I bought a Bluetooth adapter :  Asus USB-BT500 and plugged it to the reTerminal, it is recognized and I can scan bluetooth devices. 
Does that mean that I have problem with the hardware in reTerminal or maybe I need to change some configurations in order to use bluetooth with the ReTerminal's hardware ?

**Comment by MatthewJeffson** [comment]
Hi, depend on your logs, are you using reTerminal instead of reTerminal DM?
And our colleague has tested it which should be fine:
![WXWorkCapture_16968230072700](https://github.com/Seeed-Studio/wiki-documents/assets/104187183/34c9a84b-480f-41b5-a4d8-25d303af14bb)

Would you mind checking on your antenna and see whether it is connected?
