### ISSUE TITLE
[Real Life Improvement] Develop a three-dimensional Home Assistant display

### ISSUE THREAD

**Issue by MatthewJeffson** [Seeed-Studio/wiki-documents#696]
# This assignment has been successfully achieved 🎉

Thanks Tim and the wiki page is: https://wiki.seeedstudio.com/xiao-esp32c3-prism-display/

## Overview
- We need your ideas to make the Home Assistant into a three-dimensional control.
- We are trying and need you help to make the local control interactions more interesting.
## What we are trying to present:
1. Using different ways to make the control interactions more vivid.
2. The control parts can be extended by other sensors, like [Grove - gesture sensor](https://www.seeedstudio.com/Grove-Smart-IR-Gesture-Sensor-p-5721.html)
reference:
[Using prism to make a pseudo-virtual reality](https://www.youtube.com/watch?v=dZK4WjdVHo8)
## How do we work together?
- **Leave a comment with your GitHub name below** as you accept this assignment and will complete the contents about what we are trying to manage.
- The assignees can discuss here with comments or any social communication.
- Once the assignment has been completed, we might need video of the presence and the code as well.
- There are no needs for additional wiki contents like the original Contributor Program requirements.
## What do we offer?
We want to express our gratitude to our contributors by offering a range of rewards.  Depending on the difficulties(Tier 0/1/2/3), the time we expect(Days 1/3/7/15),  the actual  submission time and the actual submission contents, we will offer different levels of rewards.
1. We will provide our products or cash bonus to our contributors as a token of appreciation.
2. For those contributors who join our "Ranger Program"(announced soon), we offer even more exciting rewards, including access to our prototype products.
3. In addition, all contributors and their contributions will be acknowledged and showcased on our wiki platform.
## FAQ
- For any question, the contributor can directly commend here.
### I think I can complete the assignment, but I need more time?
- The timeframe here is based on our old experience, from people who has done it or something like that.
- However, **many projects will take much more time** under actual circumstances (including the main language of the contributors receiving the task and the actual creative difficulty)
- You can leave the time you need and a brief reason, we will evaluate the situation accordingly.

**Comment by Timo614** [comment]
Hey Matthew,

So what I was thinking here was:
- 50x50mm prism
- Xiao ESP32C3
- Grove Smart IR Gesture Sensor
- 2.2 inch square screen

For the device itself I was thinking a 3D printed enclosure that holds the prism and the screen at a slight tilt giving a nice viewing angle similar. Beneath that the gesture sensor will have its camera visible allowing for gesture based controls. 

Control capabilities:
https://wiki.seeedstudio.com/grove_gesture_paj7660/#gesture-types

Suggested initial controls:
- Swipe left and right to switch screens
- Pinch for selection
- Rotation of finger for adjusting options on a given screen

So for an instance if one screen had an arc visible to control a smart home light one could swipe to that screen, pinch to select enabling the arc control, rotate your finger to move the selector, pinch to set the final value.

Initial screens:
- Animated browser
- Cryptocurrency tracking screen (showing the state of given coins)
- Home (default)
- Configuration

Animated browser:
- Loads with pages for each imported image
- Rotation with finger to cycle through the pages
- Pinching to hide the rest of the UI like page select to only show the image
- Initial images: Fire, Rain, Snow, Cloudy, Sunny, Thunderstorm, etc.
- A readme page indicating how to import images for the browser such that users can import their own animated gifs for display

The goal of this page is primarily to allow users the ability to take advantage of the device screen for the purposes of displaying neat animations while still using this firmware.

Cryptocurrency:
- Was thinking here to use the rotational feature when on the page to switch between subpages (with subpage shown via a numeric indicator ie: 5/20), the subpage would be remembered if the user switched back to that page as well
- A separate page for each main cryptocurrency Bitcoin, Ethereum, etc. with the 24 hour change visible with an arrow pointing up or down

Home:
- Clock displayed at the bottom of the screen (perhaps clock fades away if sensor doesn't detect user after a period and fades back after a short period when the user appears to give that first impression of just the visual effect of the weather)
- Animated weather displayed above clock area on screen (clouds passing for cloudy, snow, rainstorm, thunderstorm as needed)
- Temperature and humidity shown along with clock

```
  WEATHER
|         |
 Clock T H
```

Was thinking in this way the animated weather is given the main focus here.

Configuration:
- Controls
-- Rotate finger to select a specific element
-- Pinch to begin editing the value (ie switching 24 hour clock dropdown into a list mode)
-- Rotate finger to select between choices
-- Pinch to select
- 24 hour clock select dropdown
- Brightness select slider
- Clock behavior (fade on inactivity, always show)
- Potentially screensaver picking from the full animation list (sans weather options) and the timing for how long the screensaver waits to turn on

Subsequent potential followup enhancements:
- Create screen to control devices via home assistant (similar to SenseCAP Indicator https://github.com/Seeed-Solution/SenseCAP_Indicator_ESP32/tree/main/examples/indicator_ha)
- Stock ticker screen of some form (similar to the cryptocurrency tracker so feels redundant here)
- Integration with Google calendar for a list of events for the day
- Tamagotchi-esc pet could be added and simple actions like feeding, taking care, etc. could be done. The unique nature of the screen here makes for a more compelling experience for something like this.

I'll keep brainstorming. I think these features would make for an initial really cool prism display for a home assistant.

**Comment by MatthewJeffson** [comment]
Hi @Timo614 Tim! That just amazing!  Detailed, vivid, thoughtful, skilled ideas you are sharing here. The best and the specific contents I have ever seen. 
Let us keep brainstormXD
Best Regards,
Matthew

**Comment by Timo614** [comment]
Hey, just wanted to leave an update. I've put together some 3D models in fusion to represent the various elements and put together a design I'm going to print out and test.

I have a seeed grove shield laying around and thought it may work well here so trying this approach. Going to solder some additional female headers to it and then make the connections to the LCD screen with male to female jumper wires. Will attach the gesture sensor using a grove hy 2.0 cable. The LCD screen is screwed into the top piece.

Need to confirm how well it'll print (I'll need to use some supports). Just my first attempt at it so may need to alter it further if I made any mistakes as well with the measurements.

![PrismBuddy v6-2](https://github.com/Seeed-Studio/wiki-documents/assets/1319304/f42677aa-e2f5-4a71-9a4d-a2d8d4b293dc)
![PrismBuddy v6](https://github.com/Seeed-Studio/wiki-documents/assets/1319304/8c364f74-9a5f-472b-98a1-aa101ea07e94)
![PrismBuddy v6-4](https://github.com/Seeed-Studio/wiki-documents/assets/1319304/48648a99-4eac-42c4-81d9-357a710aae19)

Underside of top with screwholes for screen:
![PrismBuddy v6-3](https://github.com/Seeed-Studio/wiki-documents/assets/1319304/2f6fb1f7-d5c8-48d5-afd9-d71af94295b0)

**Comment by MatthewJeffson** [comment]
Wow! @Timo614  Tim! This looks very nice!
I might know someone who might be able to come up with some thoughts
Best Regards,
Matthew

**Comment by Timo614** [comment]
Sounds great,

I'm in the process of printing things out and adjusting sizes (some of my
screw holes were a bit off from my measurements so needing to adjust).
Should be able to get started on the firmware soon and will leave some
updates in the thread.

Will update the thread once I have it all together for the 3D print, hoping
to start on the firmware shortly as well (figured the case was the best
call to ensure the alignment with the screen),

Tim

**Comment by Timo614** [comment]
Sorry for the delay, I should have a lot more time available in a week or so to focus a bit more intensely here -- it's the Thanksgiving Holiday in the states so have been traveling a bit.

I've worked on a few iterations of the 3D printed component and am mostly set there (I had the sensor upside down which I've since corrected and adjusted a few of the sizes / fit to work better).

![20231124_151014](https://github.com/Seeed-Studio/wiki-documents/assets/1319304/67c6b5fa-0eb1-452e-bacb-9fac566a69fa)

**Comment by MatthewJeffson** [comment]
Hi @Timo614 Tim! It is really nice work! And no worry about the timeline, you can stick to your time schedule. 
Hope you had a great and relax trip? haha
Best Regards,
Matthew

**Comment by Timo614** [comment]
Hi there Matthew,

Sorry again for the delay here but I've begun here:
https://github.com/Timo614/xiao-prism-buddy

Initially it is just the platform.io setup with associated libraries and I have the starfield demo running on the screen with it mirrored such that it displays properly when it's connected with the prism. I'll be adding the application itself and associated features over the next few days so will update here as I make more progress.

**Comment by MatthewJeffson** [comment]
Hello Tim!
Nice thing you have done here! It is been quite a time that I haven't hear from you and got a little worry haha
Thank you for the progress updated!
Best Regards,
Matthew

**Comment by Timo614** [comment]
Sounds good. Sorry about that. Trying to get lvgl working with the esp32c3
but running into a few issues with the drivers and version compatibilities
but hoping to resolve those soon and iterate from there.

**Comment by Timo614** [comment]
I've pushed up a revision that adds esp idf support (was originally using arduino as I was struggling a bit with lvgl with esp idf given driver support across versions and some incompatibilities).

Adding support for the gesture sensor triggering view events next and will start adding the views once that's in place.

**Comment by Timo614** [comment]
I've forked the main repo and added esp idf support (switching out the Arduino Wire, etc.), tested via the included example app:
https://github.com/Cosmic-Bee/Grove_Gesture

I have all the main pieces in place now so it's just a matter of building out the logic.

**Comment by MatthewJeffson** [comment]
Wow! Nice, So glad it is you doing itXD
Thank you very much.
Really looking for the outcome!
Best Regards,
Matthew

**Comment by Timo614** [comment]
I have this mostly set now from a UI perspective for the first iteration. I just am working through the last elements of the model (need to hook things up to a few web services, etc) and need to further refine the enclosure.

**Comment by MatthewJeffson** [comment]
Wow! Nice and thank you for the keep maintaining. So glad that we are getting there closer and closer XD

**Comment by Timo614** [comment]
I have the app pretty much setup now for the initial setup. I need to rework the enclosure a bit and make sure it all fits snugly but should be otherwise ready to go. I have the wifi credentials setup as part of menuconfig for the sdkconfig variables there and once it loads it fetches the user's IP address, city, weather, bitcoin information, and updates the display accordingly. It listens for sensor input for changing screens and selecting inputs.

I'll put together a wiki for its install and usage once I have the enclosure set.

**Comment by Timo614** [comment]
![prism-xiao-v32](https://github.com/Seeed-Studio/wiki-documents/assets/1319304/e9fa0d41-079c-4245-a8e1-d9375410ef3c)

Making progress on the enclosure. I'm printing out this version above currently with some adjustments from my earlier iterations (I had to adjust for some minor sizing issues and to give a little more leeway). I'm not an expert with 3D design so may take a few more iterations in case I made some of the tolerances too tight, etc.

**Comment by Timo614** [comment]
Sorry again for the delay, been a pretty hectic period here with sick season and with the end of winter break for my kids. I should be able to wrap this up in the next few days (I haven't been able to touch it much lately).

**Comment by MatthewJeffson** [comment]
Hello @Timo614 ! No worry at all! Yes indeed it is easy getting sick time and hope you and your family are well.
Best Regards,
Matthew

**Comment by Timo614** [comment]
I was able to get everything together here and screwed in with some m2 screws.

One thing I noticed was when the gesture sensor is in place it is unable to detect gestures, however. I think I need to give a lot more room around the sensor camera and IR LEDs so I'll need to print a new version with that but otherwise things seem to be working for me.

![20240115_114244](https://github.com/Seeed-Studio/wiki-documents/assets/1319304/187ee6a1-9a0a-4925-bcad-cc41371c4c02)
![20240115_114248](https://github.com/Seeed-Studio/wiki-documents/assets/1319304/16d10b38-f047-4aaa-a509-e729b00b5606)
![20240115_114253](https://github.com/Seeed-Studio/wiki-documents/assets/1319304/f15e3d14-8af5-46e4-b0b8-09a68d64cafb)
![20240115_114649](https://github.com/Seeed-Studio/wiki-documents/assets/1319304/330002a0-20f0-4ef9-91c9-b014d396e807)
![20240115_114700](https://github.com/Seeed-Studio/wiki-documents/assets/1319304/f8cf5c2c-733e-47dd-aa2c-54c706406dbd)

**Comment by MatthewJeffson** [comment]
Wow NICE! Perfect!

**Comment by Timo614** [comment]
Just tried with a wider window around the camera and IR lights but still running into some issues picking up the gestures with a wider cutout so going to keep at it and adjust it further (some of the gestures were working but not fluidly / the grab and rotate were ignored while in this enclosure). It works outside of the enclosure for those gestures so likely just a matter of getting the positioning right.

**Comment by MatthewJeffson** [comment]
Ah~ I see, maybe consider let the sensor be exposed?

**Comment by Timo614** [comment]
I've gone ahead and switched it, https://www.youtube.com/watch?v=vdHHd5qkkdo

I need to make a few minor modifications to sizing to fit the sensor a bit better, need to flip the display, need to change the default brightness level, and I think I should switch the gestures as the rotation and grab ones sometimes work sporadically (the left and right work consistently). I did notice the 1, 2, 3, 4 fingers worked well from my testing so may use that to designate setting screens and will think of a good rotation replacement for that element.

**Comment by Timo614** [comment]
https://youtu.be/wSJa8HP0BkM

I reworked the enclosure a bit to better fit the gesture scanner in front and noticed it seems to be handling the rotation and grab gestures a lot better. I think it may have been an issue with it not aligning correctly from not fitting properly. It still can be a bit finicky but appears to work here.

Do you want me to add a project page associated with this on the wiki? Can include a video for setup in addition to the above video with some information and the steps required to get it up and running.

**Comment by MatthewJeffson** [comment]
The presentation looks amazingly great! Wow! Nice work! That is beyond my expectation:o!

**Comment by MatthewJeffson** [comment]
And yes, @Timo614 would you mind adding this into the wiki? This is the [template](https://wiki.seeedstudio.com/Name_your_website/).
