### ISSUE TITLE
[Page Add][Enhanced Function]Add XIAO boards in to Flux.ai

### ISSUE THREAD

**Issue by MatthewJeffson** [Seeed-Studio/wiki-documents#702]
# This assignment has been successfully achieved 🎉

Thanks Gokul and the wiki page is: https://wiki.seeedstudio.com/PCB_Design_XIAO/

with launched page: https://www.flux.ai/seeedstudio

## Overview
- We need your help to add required Boards in the [Flux.ai](https://www.flux.ai/p).
- And we need some instructions guidelines.
## Batches
We have continued products wanted to be presented on Flux.ai.
### Fifth Batch
Present the Seeed Studio products below on Flux.ai:
       - [Grove Vision AI V2 sensor](https://www.seeedstudio.com/Grove-Vision-AI-Module-V2-p-5851.html)
       - [Wio-E5-LE mini Dev Board](https://www.seeedstudio.com/Wio-E5-LE-mini-Dev-Board-STM32WLE5JC-p-5764.html)
       - [Wio-WM1110 Dev Kit](https://www.seeedstudio.com/Wio-WM1110-Dev-Kit-p-5677.html)
### Fourth Batch
Present the Seeed Studio products below on Flux.ai:
       - Wio-E5 mini Dev Board
       - Wio-E5 Dev Kit
       - Wio-E5-LE Wireless Module.
### Third Batch
Present the Seeed Studio products below on Flux.ai:
       - WM1302 module
       - WM1110 module
### Second Batch
Present the Seeed Studio products below on Flux.ai:
       - Wio Terminal board
       - Grove modules
### First Batch
1. Present all Seeed Studio XIAO boards on the Flux.
2. From the beginning, introduce how to add / customize the 3D models of the board into Flux.ai and writing us a wiki.
3. The wiki should be stored in docs/Sensor/SeeedStudio_XIAO

Reference:
- [XIAO SAMD21 on Flux.ai](https://www.flux.ai/cnaville89/seeed-xiao-samd21?editor=pcb_3d)
- [Move your KiCAD parts into Flux](https://www.youtube.com/watch?v=eplpLndGfvk)

## How do we work together?
- **Leave a comment with your GitHub name below** as you accept this assignment and will complete the contents about what we are trying to present.
- The maintainer will assign and record you as our only contact for this assignment.
- You can first [Deploy this Wiki Platform Locally](https://wiki.seeedstudio.com/Deploy_Page_Locally/) (The entire source code .zip file is only 30 M)
- You will be invited as our **"Contributor"** once you ["Pull Request"](https://wiki.seeedstudio.com/Contribution-Guide/).
- The maintainer will review the PR and then merge.
## What do we offer?
We want to express our gratitude to our contributors by offering a range of rewards.  Depending on the difficulties(Tier 0/1/2/3), the time we expect(Days 1/3/7/15),  the actual  submission time and the actual submission contents, we will offer different levels of rewards.
1. We will provide our products or cash bonus to our contributors as a token of appreciation.
2. For those contributors who join our ["Ranger Program"](https://www.seeedstudio.com/blog/2023/09/15/join-the-seeed-ranger-program-empowering-developers-and-building-communities/), we offer even more exciting rewards, including access to our prototype products.
3. In addition, all contributors and their contributions will be acknowledged and showcased on our wiki platform.
## FAQ
- For any question, the contributor can directly commend here.
### I think I can complete the assignment, but I need more time?
- The timeframe here is based on our old experience, from people who has done it or something like that.
- However, **many projects will take much more time** under actual circumstances (including the main language of the contributors receiving the task and the actual creative difficulty)
- You can leave the time you need and a brief reason, we will evaluate the situation accordingly.

**Comment by gokuxmaker** [comment]
Gokul

**Comment by gokuxmaker** [comment]
**Fifth Batch**
[Grove Vision AI Module V2](https://www.flux.ai/seeedstudio/grove-vision-ai-module-v2)
[Wio-E5-LE mini Dev Board ](https://www.flux.ai/seeedstudio/wio-e5-le-mini-dev-board)
[Wio-WM1110 Dev Kit ](https://www.flux.ai/seeedstudio/wio-wm1110-dev-kit)
**Fourth Batch**
[Wio-E5 mini Dev Board](https://www.flux.ai/seeedstudio/wio-e5-mini-dev-board)
[Wio-E5 Dev Kit ](https://www.flux.ai/seeedstudio/wio-e5-dev-kit)
[Wio-E5-LE Wireless Module](https://www.flux.ai/seeedstudio/wio-e5-le-wireless-module)
**Third Batch**
[LoRaWAN® Gateway Module WM1302](https://www.flux.ai/seeedstudio/lorawanr-gateway-module-wm1302)
[Wio-WM1110 Wireless Module ](https://www.flux.ai/seeedstudio/wio-wm1110-wireless-module)
**Second Batch**
[Seeed Studio Wio Terminal](https://www.flux.ai/seeedstudio/seeed-studio-wio-terminalp)
[Grove - CO2 & Temperature & Humidity Sensor (SCD30)](https://www.flux.ai/seeedstudio/grove-co2-and-temperature-and-humidity-sensor-scd30)
_Done !_

**Comment by MatthewJeffson** [comment]
NICE Work! @filmferry
