### ISSUE TITLE
[Real Life Improvement] Build a Smart Thermostat with Seeed Studio XIAO Boards and integrated with Home Assistant

### ISSUE THREAD

**Issue by MatthewJeffson** [Seeed-Studio/wiki-documents#726]
# This assignment has been successfully achieved 🎉

Thanks Chris and the wiki page is: https://wiki.seeedstudio.com/esp32c3_smart_thermostat/

## Overview
- We are trying to present a programmable smart thermostat for the real life improvement, by Home Assistant.
- We need your help to use Seeed Studio XIAO boards and Grove modules to come up with a prototype.
- reference 
     - [EcoStat made by Chris](https://github.com/Echo7394/EcoStat#ecostat)
## How do we work together?
- **Leave a comment with your GitHub name below** as you accept this assignment and will complete the contents about what we are trying to present.
- The maintainer will assign and record you as our only contact for this assignment.
- You can first [Deploy this Wiki Platform Locally](https://wiki.seeedstudio.com/Deploy_Page_Locally/) (The entire source code .zip file is only 30 M)
- You will be invited as our **"Contributor"** once you ["Pull Request"](https://wiki.seeedstudio.com/Contribution-Guide/).
- The maintainer will review the PR and then merge.
## What do we offer?
We want to express our gratitude to our contributors by offering a range of rewards.  Depending on the difficulties(Tier 0/1/2/3), the time we expect(Days 1/3/7/15),  the actual  submission time and the actual submission contents, we will offer different levels of rewards.
1. We will provide our products or cash bonus to our contributors as a token of appreciation.
2. For those contributors who join our "[Ranger Program](https://www.seeedstudio.com/blog/2023/09/15/join-the-seeed-ranger-program-empowering-developers-and-building-communities/)", we offer even more exciting rewards, including access to our prototype products.
3. In addition, all contributors and their contributions will be acknowledged and showcased on our wiki platform.
## FAQ
- For any question, the contributor can directly commend here.
### I think I can complete the assignment, but I need more time?
- The timeframe here is based on our old experience, from people who has done it or something like that.
- However, **many projects will take much more time** under actual circumstances (including the main language of the contributors receiving the task and the actual creative difficulty)
- You can leave the time you need and a brief reason, we will evaluate the situation accordingly.

**Comment by Echo7394** [comment]
I accept! I have responded to your E-Mail with further details, please let me know if you need any other information from me at this time. Thank you!

**Comment by MatthewJeffson** [comment]
Nice and thank you as well!
Really looking forward the cooperation:D

**Comment by gokuxmaker** [comment]
I am also interested in it . I will help you to design PCB, 3D printable enclosure, UI\Ux design( oled or lcd )

**Comment by Echo7394** [comment]
Thank you for your offer! Although I do already have those steps complete, if I run into any issues I will reply with further questions!

**Comment by Echo7394** [comment]
@MatthewJeffson Just wanted to post a quick check-in here: The configuration/code for ESPHome is complete, as well as testing all the hardware and verifying that everything works as desired. I will be printing the case, putting together the demo, and finalizing the project within the week!

**Comment by MatthewJeffson** [comment]
@Echo7394 Hello! Chris! That is great news! Really looking forward to it!
Best Regards,
Matthew

**Comment by Echo7394** [comment]
Quick question for you. On https://wiki.seeedstudio.com/Contribution-Guide/ it shows that content for the Pull request should be uploaded in "/docs/Contribution/Contributors/file_transfer_station/"create a folder to store your files".

I do not see any folder called "file_transfer_station" in the Contributors directory. Can you provide some guidance?

**Comment by MatthewJeffson** [comment]
Hello @Echo7394 Chris! Glad to hear from you!
The "file_transfer_station" folder will be created and named by you:D
I just made an example here.
After you PR, I will get your images from the folder and put them all in our server then convert them as urls.
And this is the reason that you find the image on this wiki platform are basically urls: 


![Image](https://github.com/Seeed-Studio/wiki-documents/assets/104187183/e4014a8b-752f-4d7c-9b3a-c34fa0f5a7c7)


Hope this can be helpful.
Best Regards,
Matthew

**Comment by Echo7394** [comment]
My apologies that I am not fully understanding the contribution guide fully. Am I correct to assume that I upload all the files to a directory such as "/docs/Contribution/Contributors/file_transfer_station/XIAO_ESP32C3_ESPHome_Smart_Thermostat" and then use the files there as the source directory to create a new wiki page within "wiki-documents/docs/Topics/Home_Assistant/Home_Assistant_Tutorials"? The contribution guide is a bit vague on exactly what I am supposed to do.

**Comment by MatthewJeffson** [comment]
Yeah, my apologies as well regarding the guide here...
But you understand is right: upload the files into the directory. 
What I meant was all the files: including the ".md" file and all the images you used in the ".md" files



![Image](https://github.com/Seeed-Studio/wiki-documents/assets/104187183/1dec3e93-3662-4acd-8705-2f54df1e4dc7)

After you PR, I will review it and do the changes from our side.

The process is not complete and I'm so sorry about the confusion and time-waste...

Let me know if you have any question.

Best Regards,
Matthew

**Comment by Echo7394** [comment]
One last question, since I am not editing a page that previously exists within the wiki. I cannot see a live preview of the page i am creating. Is there a step im missing to add the page to the wiki. Or should I just proceed with making an entirely new .md and use a preexisting page as a template and let you finalize the look later?

**Comment by MatthewJeffson** [comment]
Yes, creating a new one wiki (a new .md file) is required. As you can see one the top of the .md file. The "slug" content represents the url and you can use it to preview what you are writing.

<img width="683" alt="image" src="https://github.com/Seeed-Studio/wiki-documents/assets/104187183/e10b7d19-9d14-4a57-a99f-d0925186cf0d">

If you are confused, sending the files to me is really fine. I will take care of it.
Best Regards,
Matthew

**Comment by Echo7394** [comment]
Nope thank you, I understand now! Finalizing tonight!

**Comment by Echo7394** [comment]
@MatthewJeffson Pull request submitted!

**Comment by MatthewJeffson** [comment]
WOW! @Echo7394  Nicely done! We will review it very soon.
Thank you so much for doing it!:D
Best Regards,
Matthew

**Comment by Echo7394** [comment]
It was a very fun project, thank you for all of your help! Sorry for the delay, holiday season has been quite busy.

**Comment by MatthewJeffson** [comment]
No worry at all! I really appreciate your hard work! 
May we can discuss the compensation regarding it:D I think I have sent an email about it. Have you received it?

**Comment by Echo7394** [comment]
I'm not completely sure. I will look through previous emails to check.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by Echo7394** [comment]
What account information specifically do you need?

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by Echo7394** [comment]
If it's easier for you I'd gladly trade my compensation for a device such as the reRouter: https://www.seeedstudio.com/reRouter-CM4102032-p-5734.html?queryID=8e2212299f62d7a947ee003652e7d78d&objectID=5734&indexName=bazaar_retailer_products

If not let me know what info you need.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by MatthewJeffson** [comment]
Oh okay, definitely we can arrange that:D
I will make the deliver after we back next year.
Happy New Year!
Best Regards,
Matthew

**Comment by Echo7394** [comment]
Thank you very much!

Sent from Proton Mail mobile

-------- Original Message --------
