### ISSUE TITLE
Connect T1000-1 to The Things Network - Clarification Needed

### ISSUE THREAD

**Issue by rei-vilo** [Seeed-Studio/wiki-documents#797]
[Step 2: Register the Device](https://wiki.seeedstudio.com/SenseCAP_T1000_tracker_TTN/#step-2-register-the-device) of the procedure [Connect to The Things Network](https://wiki.seeedstudio.com/SenseCAP_T1000_tracker_TTN) is confusing.

+ The SenseCAP Mate APP provides `Device EUI`, `APP EUI` and `APP Key` as shown on the picture below…

![tracker_appconfig](https://github.com/Seeed-Studio/wiki-documents/assets/951776/352664ab-8ce5-49e6-95e6-0870be6503c9)

+ while The Things Network asks for `Join EUI`, `Dev EUI` and `APP Key`.

![add_new](https://github.com/Seeed-Studio/wiki-documents/assets/951776/0a8ee87b-d9d9-4770-a788-52b4ddafe295)

The picture below shows the same code, actually `APP EUI`, on the three fields on The Things Network page.

Could you please clarify [line 66](https://github.com/Seeed-Studio/wiki-documents/blame/b5997aeaac61bcc06fd8219db5c1ee8dcfede6d9/docs/Sensor/SenseCAP/SenseCAP_T1000_Tracker/Integrated_with_LoRaWAN_Network_Server/Connect_to_The_Things_Network.md#L66)?

Thank you!

**Comment by rei-vilo** [comment]
[Step 2: Register the Device](https://wiki.seeedstudio.com/SenseCAP_T1000_tracker_TTN/#step-2-register-the-device) of the procedure [Connect to The Things Network](https://wiki.seeedstudio.com/SenseCAP_T1000_tracker_TTN) is confusing.

+ The SenseCAP Mate APP provides `Device EUI`, `APP EUI` and `APP Key` as shown on the picture below…

![tracker_appconfig](https://github.com/Seeed-Studio/wiki-documents/assets/951776/352664ab-8ce5-49e6-95e6-0870be6503c9)

+ while The Things Network asks for `Join EUI`, `Dev EUI` and `APP Key`.

![add_new](https://github.com/Seeed-Studio/wiki-documents/assets/951776/0a8ee87b-d9d9-4770-a788-52b4ddafe295)

The picture below shows the same code, actually `APP EUI`, on the three fields on The Things Network page.

Could you please clarify [line 66](https://github.com/Seeed-Studio/wiki-documents/blame/b5997aeaac61bcc06fd8219db5c1ee8dcfede6d9/docs/Sensor/SenseCAP/SenseCAP_T1000_Tracker/Integrated_with_LoRaWAN_Network_Server/Connect_to_The_Things_Network.md#L66)?

Thank you!

**Comment by Jessie219-web** [comment]
the `JoinEUI` formerly called `AppEUI`, they are the same thing

**Comment by rei-vilo** [comment]
Thank you! Would you mind update the wiki page accordingly?

**Comment by MatthewJeffson** [comment]
Hi! The contents have been added.
