### ISSUE TITLE
Documentation for setting up senseCAP with HA is not concise 

### ISSUE THREAD

**Issue by fabianmuehlberger** [Seeed-Studio/wiki-documents#810]
In [seneCAP wiki](https://wiki.seeedstudio.com/SenseCAP_Indicator_Application_Home_Assistant/#build-and-flash-the-native-firmware), the project configuration is described as: 
1. Configure IP address: 
* It can only be assumed that it is meant to clone the repository first before starting with step 1. Since the files to be edited are not present in HA. 
 
Under Step 2, the setting of username and password is described as: 

```
If you have a username and password, you will need to configure them. This can be done in the mqtt_start function in the indicator_ha.c file, specifically in the mqtt_cfg configuration. If you do not have a username and password, you can comment them out.

Here is an example of how to configure the username and password:


    esp_mqtt_client_config_t mqtt_cfg = {
        .broker.address.uri = CONFIG_BROKER_URL,
        .credentials.username = "MQTT_Indicator_1", // Your Home Assistant user
        .credentials.authentication.password = "kjdf", // user's password
    };
```
The actual indicator_ha.c file does not have a `mqtt_start` function, I'm not sure if the intention is to use the `ha_config.h` file to set the MQTT username and password below the CONFIG_BROKER_URL, but this seems to be a better place.

**Comment by Love4yzp** [comment]
Hey there,

Just wanted to give you a heads-up that our Wiki is getting some updates to match with the latest code changes.

About your query on the mqtt_start function and MQTT settings - you're on point noticing some discrepancies in the current HA code. The code you need is in a specific commit of our repo. Check it out here: [SenseCAP Indicator ESP32](https://github.com/Seeed-Solution/SenseCAP_Indicator_ESP32/tree/459fb0b8de1b8c823385e5185b5fdb482aed80c9). The mqtt_start function is in the indicator_ha.c file, and you can find it directly via this link: [indicator_ha.c at commit 459fb0b](https://github.com/Seeed-Solution/SenseCAP_Indicator_ESP32/blob/459fb0b/examples/indicator_ha/main/model/indicator_ha.c).

For the MQTT username and password setup, note that ha_config.h comes with hardcoded values. 

We're working on getting all the docs up to date.

And, I've noticed there are some issues with the latest HA firmware. For now, I suggest using this version to explore Home Assistant applications.  Also, you might want to try out this community application I came across – it's pretty cool and could be useful for your setup: [SenseCapConfig on GitHub](https://github.com/YooSHome/SenseCapConfig). Definitely worth a look!

**Comment by fabianmuehlberger** [comment]
Hey, 
since I have been looking for a display/HMI for home use for a while now, the senseCap looks already very promising, am I am sure it will be a fantastic complement to the smart home community.  
If I can assist with some tests or help to document, please let me know!

Best 
Fabian

**Comment by MatthewJeffson** [comment]
Hi! @fabianmuehlberger Fabian! It is been a pleasure to meet you and we will be honored to have you onboard:D
Before we proceeding anything, may I have your technological background and what kinds of products you used before?
We can discuss through the Email and here is mine: jianfeng.yu@seeed.cc
Best Regards,
Matthew
