### ISSUE TITLE
In the LoRa-E5 page, add a note about which pins are Rx/Tx (PB6 and PB7)

### ISSUE THREAD

**Issue by DeflateAwning** [Seeed-Studio/wiki-documents#838]
On the [LoRa-E5 page](https://wiki.seeedstudio.com/LoRa-E5_STM32WLE5JC_Module/), in the table that says `Usart1(PB6/PB7)`, change that cell to read:

```
USART1: PB6=TX, PB7=RX
```

Thanks!

**Comment by MatthewJeffson** [comment]
It is been fixed.
