### ISSUE TITLE
[Page Add][Enhanced function] Build a car OBD with XIAO ESP32C3 and XIAO CAN Bus Expansion Board

### ISSUE THREAD

**Issue by MatthewJeffson** [Seeed-Studio/wiki-documents#854]
## This Project has been achieved!

The project link is: https://github.com/alooox/krispy_gauge

## Overview
- We need your help to build a car OBD with XIAO ESP32C3 and XIAO CAN Bus Expansion Board and write a wiki regarding it.
- reference:

![Image](https://github.com/Seeed-Studio/wiki-documents/assets/104187183/f8ed3fd4-1c3e-4e70-8650-37b5d14aa2fc)

- [Template for wiki contents](https://wiki.seeedstudio.com/Name_your_website/)
## How do we work together?
- **Leave a comment with your GitHub name below** as you accept this assignment and will complete the contents about what we are trying to present.
- The maintainer will assign and record you as our only contact for this assignment.
- You can first [Deploy this Wiki Platform Locally](https://wiki.seeedstudio.com/Deploy_Page_Locally/) (The entire source code .zip file is only 30 M)
- You will be invited as our **"Contributor"** once you ["Pull Request"](https://wiki.seeedstudio.com/Contribution-Guide/).
- The maintainer will review the PR and then merge.
## What do we offer?
We want to express our gratitude to our contributors by offering a range of rewards.  Depending on the difficulties(Tier 0/1/2/3), the time we expect(Days 1/3/7/15),  the actual  submission time and the actual submission contents, we will offer different levels of rewards.
1. We will provide our products or cash bonus to our contributors as a token of appreciation.
2. For those contributors who join our "Ranger Program"(announced soon), we offer even more exciting rewards, including access to our prototype products.
3. In addition, all contributors and their contributions will be acknowledged and showcased on our wiki platform.
## FAQ
- For any question, the contributor can directly commend here.
### I think I can complete the assignment, but I need more time?
- The timeframe here is based on our old experience, from people who has done it or something like that.
- However, **many projects will take much more time** under actual circumstances (including the main language of the contributors receiving the task and the actual creative difficulty)
- You can leave the time you need and a brief reason, we will evaluate the situation accordingly.

**Comment by alooox** [comment]
Alex

**Comment by Priyanshu0901** [comment]
Hi @MatthewJeffson,

I recently discovered Seed's contributor program and am eager to contribute. With almost 2 years of professional experience, I specialize in building libraries for microcontrollers such as ESP32 (ESP-IDF), STM32, Atmega Series, etc.

I'm keen to connect and actively participate in Seed's program. Please feel free to reach out to me at [roypriyanshu09@gmail.com](url).

Best regards,
Priyanshu

**Comment by MatthewJeffson** [comment]
@Priyanshu0901 Hello Priyanshu!
Sorry the late response! I have emailed you:D
Best Regards,
Matthew

**Comment by MatthewJeffson** [comment]
@thealexproctor Hello Alex! How is it going with the project. I have been informed that another contributor is interested to do it.:D
Best Regards,
Matthew

**Comment by alooox** [comment]
![image](https://github.com/Seeed-Studio/wiki-documents/assets/53038455/b5c370f9-9c71-46b1-b968-e478d4454db2)
![image](https://github.com/Seeed-Studio/wiki-documents/assets/53038455/a1e68865-0417-4873-aa55-cde720c37e19)
![image](https://github.com/Seeed-Studio/wiki-documents/assets/53038455/09beca2d-984b-4493-ae90-6fc279e31f31)

Working well, was taking a little while as I was waiting for some more ESP32C3 boards as they were on backorder, but getting design more finalised.

**Comment by alooox** [comment]
Also Custom PCB's @MatthewJeffson

**Comment by MatthewJeffson** [comment]
@thealexproctor WOW! Alex! That was amazing!

**Comment by alooox** [comment]
Thanks @MatthewJeffson, I am really trying to finalise the design and get it working perfectly to make it as easy as possible to produce more, ive taken the assembily time down from 1.5hrs to about 30 minutes per gauge with the custom PCB. 

Could you tell me @MatthewJeffson do these displays support reading from the display? as im trying to get the TFT_espi Animated Dial example to work, but it seems to have a issue, perhaps you could clarify. 

Could you also clarify if the display supports backlight control? as I can see BL is on Pin 6 so was hoping I could send a PWM signal on Pin 6 to control the backlight but this does not seem to work.

**Comment by MatthewJeffson** [comment]
Hello! @thealexproctor Alex! Reducing time to assemble is looking very promising!
Regarding the TFT_espi and backlight control, I will contact my colleagues to see if there is anything that we can help with:)
Really nice work!The design is truly impressed!
As we updated the [ODM service](https://www.seeedstudio.com/odm.html), we will contact the related colleagues as well to see how the progress is going.
Best Regards,
Matthew

**Comment by alooox** [comment]
Hi @MatthewJeffson how did you go regarding finding out about the display? Would love to deep dive into some extra functionality.

**Comment by MatthewJeffson** [comment]
Hello @thealexproctor Alex! I am so sorry for long time not reply. Things been crazy lately.XD
1. The backlight control only supports "on" and "off" and can not be controlled by PWM.
2. And for the "TFT_espi Animated Dial" example, my colleague has tested it and it seems ETA3410 not supporting pixel reading function.

We have set up a discord channel and would you mind joining us? for the instant communication?
Best Regards,
Matthew

**Comment by alooox** [comment]
Sure, can you email me a link? I might already be in it

**Comment by MatthewJeffson** [comment]
Hey lo! I have sent you the link @thealexproctor :D

**Comment by MatthewJeffson** [comment]
Is everything going well? @thealexproctor Alex? Since we are quite long time not hearing from you:D
Best Regards,
Matthew

**Comment by MatthewJeffson** [comment]
This assignment be reopened

**Comment by MatthewJeffson** [comment]
Hello! @alooox Alex! I can see you have finished it! Amazing! https://github.com/alooox/krispy_gauge
Would you mind we sharing this project on our social media?
Best Regards,
Matthew

**Comment by alooox** [comment]
Hi Matthew, sorry I have been away for some time, I actually created my own
github repo for this project too, so currently trying to work out how to
add the changes to your git repo, I dont use git often, so is tricky for
me.

**Comment by MatthewJeffson** [comment]
No worry about it! Here is my Discord ID and we can communicate directly on Discord:)

matthew_yu0310



![Image](https://github.com/user-attachments/assets/243a5288-2984-4ba4-b938-f97be6bb73c2)

**Comment by Love4yzp** [comment]
> I actually created my own github repo for this project too, so currently trying to work out how to add the changes to your git repo, I dont use git often, so is tricky for me.

Git is essential for project management, and everyone in the industry should learn it.

To understand the basics of Git, watch this video: [Git Tutorial for Beginners: Learn Git in 1 Hour - YouTube](https://www.youtube.com/watch?v=8JJ101D3knE).

After grasping the basic concepts, you can use Git extensions on VSCode or tools like SourceTree. These tools offer graphical interfaces that make it easier to manage your Git repositories.
