### ISSUE TITLE
[Question] can we use Seeed Studio XIAO ESP32S3 Sense with 1.47 or 1.69 inch LCD SPI Display ? Thank you.

### ISSUE THREAD

**Issue by selfhostrepo** [Seeed-Studio/wiki-documents#877]
can we use Seeed Studio XIAO ESP32S3 Sense with 1.47 or 1.69 inch LCD SPI Display ? Thank you.

**Comment by MatthewJeffson** [comment]
Hi, yes it supports.
Thank you for the interests in our products!:D
