### ISSUE TITLE
[Product Issue][GitHub]XIAO NFC example wrong with deprecation/removal of primo core

### ISSUE THREAD

**Issue by ohsix** [Seeed-Studio/wiki-documents#9]
https://wiki.seeedstudio.com/XIAO-BLE-Sense-NFC-Usage/

the NFC.h header & library that provided the setTXTmessage api was from the primo core https://github.com/arduino/ArduinoCore-primo/tree/cd54ab663d93e60e5a53d2d05f13f16e3cc147e7/libraries/NFC

the mbed core has an NFC.h header but it is for the initiator api, the eeprom api is still in the nrf52 sdk (and is what the primo core used) but there's no simple wrapper for it anymore

**Comment by KylianBOIDARD** [comment]
Hello,
@ohsix 
I am trying to use the NFC feature on the nrf52840 sense microcontroller. Is there any update about how to fix this issue ?
Thanks a lot for your reply

**Comment by MatthewJeffson** [comment]
The NFC library is under updating and will be published as soon as possible.

**Comment by ohsix** [comment]
that's great, but the wiki still says NFC.h and NFC.setTXTmessage is supported, and it isn't. when i filed this I thought someone would just track down a different example. that's why i linked to the primo core, and in the other bug, someone re-adding that NFC api to another core.

this should stay open until the example is fixed

**Comment by quicksketch** [comment]
Hi @MatthewJeffson, has the NFC library been fixed yet? And if so, can the notice be removed from [the NFC wiki page](https://github.com/Seeed-Studio/wiki-documents/blob/9894d94c9a00f02369bb118169d47ea824ef30cd/docs/Sensor/SeeedStudio_XIAO/SeeedStudio_XIAO_nRF52840-Sense/XIAO-BLE-Sense-NFC-Usage.md)?

EDIT: Looks like maybe this was fixed June, 2023? https://forum.seeedstudio.com/t/xiao-ble-nfc-doesnt-work/264543/8 Even if "fixed" the documentation examples may still need work.

**Comment by MatthewJeffson** [comment]
Yes indeed! The documentation will be updated soon:D
