### ISSUE TITLE
Seeed T1000 Tracker reporting incorrect Year

### ISSUE THREAD

**Issue by CropWatchDevelopment** [Seeed-Studio/wiki-documents#935]
Hello Everyone,
Ever since Jan 1st 2024, my seeed T1000 trackers have all been reporting that it is the year 2067.
I need clarity on why this may be occuring, how to fix it, and if anyone else has seen this problem.

I do see there was a newer firmware out, but it says nothing about any bug fixes, just time "optimization"
I don't believe that going from the year 2067 back to the correct time of 2024 would be considered an...
optimization by any stretch of the imagination.

Looking forward to hearing if there was a fix, or how others work around this!

**Comment by Kway99** [comment]
Hi, please open a tech support ticket and post your SN there, we will take a look and reply.https://support.sensecapmx.com/.Or you can contact us by e-mail sensecap@seeed.cc thanks!
