### ISSUE TITLE
Wrong Pin Description in 125kHz RFID Reader

### ISSUE THREAD

**Issue by elRicharde** [Seeed-Studio/wiki-documents#966]
[About that page:](https://wiki.seeedstudio.com/Grove-125KHz_RFID_Reader/#hardware)
https://wiki.seeedstudio.com/Grove-125KHz_RFID_Reader/#hardware

I had trouble reading my Dongles and it seems that you not only need to change the jumper when switching from UART to WIEGAND, in my case I also needed to change Pin 2 & 3

Find my Tests and code here
https://forum.arduino.cc/t/trouble-converting-wiegand-w26-output-to-dec/1221511

**Comment by MatthewJeffson** [comment]
Thank you so much for the question above and it seems the solution can be found here: https://forum.seeedstudio.com/t/125khz-rfid-module-simpler-wiegand-code/14634/4
I will try to inform the product manager.
Best Regards
